/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ExploreIconsParams,
  ExploreScreenshotsParams
} from '../../models';





/**
 * @summary Browse screenshots across all apps
 */
export type exploreScreenshotsResponse200 = {
  data: void
  status: 200
}

export type exploreScreenshotsResponseSuccess = (exploreScreenshotsResponse200) & {
  headers: Headers;
};
;

export type exploreScreenshotsResponse = (exploreScreenshotsResponseSuccess)

export const getExploreScreenshotsUrl = (params?: ExploreScreenshotsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/explorer/screenshots?${stringifiedParams}` : `/api/v1/explorer/screenshots`
}

export const exploreScreenshots = async (params?: ExploreScreenshotsParams, options?: RequestInit): Promise<exploreScreenshotsResponse> => {

  const res = await fetch(getExploreScreenshotsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: exploreScreenshotsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as exploreScreenshotsResponse
}





export const getExploreScreenshotsQueryKey = (params?: ExploreScreenshotsParams,) => {
    return [
    `/api/v1/explorer/screenshots`, ...(params ? [params] : [])
    ] as const;
    }


export const getExploreScreenshotsQueryOptions = <TData = Awaited<ReturnType<typeof exploreScreenshots>>, TError = unknown>(params?: ExploreScreenshotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreScreenshots>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExploreScreenshotsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof exploreScreenshots>>> = ({ signal }) => exploreScreenshots(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exploreScreenshots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExploreScreenshotsQueryResult = NonNullable<Awaited<ReturnType<typeof exploreScreenshots>>>
export type ExploreScreenshotsQueryError = unknown


export function useExploreScreenshots<TData = Awaited<ReturnType<typeof exploreScreenshots>>, TError = unknown>(
 params: undefined |  ExploreScreenshotsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreScreenshots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exploreScreenshots>>,
          TError,
          Awaited<ReturnType<typeof exploreScreenshots>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExploreScreenshots<TData = Awaited<ReturnType<typeof exploreScreenshots>>, TError = unknown>(
 params?: ExploreScreenshotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreScreenshots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exploreScreenshots>>,
          TError,
          Awaited<ReturnType<typeof exploreScreenshots>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExploreScreenshots<TData = Awaited<ReturnType<typeof exploreScreenshots>>, TError = unknown>(
 params?: ExploreScreenshotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreScreenshots>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Browse screenshots across all apps
 */

export function useExploreScreenshots<TData = Awaited<ReturnType<typeof exploreScreenshots>>, TError = unknown>(
 params?: ExploreScreenshotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreScreenshots>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExploreScreenshotsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Browse app icons across all apps
 */
export type exploreIconsResponse200 = {
  data: void
  status: 200
}

export type exploreIconsResponseSuccess = (exploreIconsResponse200) & {
  headers: Headers;
};
;

export type exploreIconsResponse = (exploreIconsResponseSuccess)

export const getExploreIconsUrl = (params?: ExploreIconsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/explorer/icons?${stringifiedParams}` : `/api/v1/explorer/icons`
}

export const exploreIcons = async (params?: ExploreIconsParams, options?: RequestInit): Promise<exploreIconsResponse> => {

  const res = await fetch(getExploreIconsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: exploreIconsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as exploreIconsResponse
}





export const getExploreIconsQueryKey = (params?: ExploreIconsParams,) => {
    return [
    `/api/v1/explorer/icons`, ...(params ? [params] : [])
    ] as const;
    }


export const getExploreIconsQueryOptions = <TData = Awaited<ReturnType<typeof exploreIcons>>, TError = unknown>(params?: ExploreIconsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreIcons>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExploreIconsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof exploreIcons>>> = ({ signal }) => exploreIcons(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exploreIcons>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExploreIconsQueryResult = NonNullable<Awaited<ReturnType<typeof exploreIcons>>>
export type ExploreIconsQueryError = unknown


export function useExploreIcons<TData = Awaited<ReturnType<typeof exploreIcons>>, TError = unknown>(
 params: undefined |  ExploreIconsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreIcons>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exploreIcons>>,
          TError,
          Awaited<ReturnType<typeof exploreIcons>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExploreIcons<TData = Awaited<ReturnType<typeof exploreIcons>>, TError = unknown>(
 params?: ExploreIconsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreIcons>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exploreIcons>>,
          TError,
          Awaited<ReturnType<typeof exploreIcons>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExploreIcons<TData = Awaited<ReturnType<typeof exploreIcons>>, TError = unknown>(
 params?: ExploreIconsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreIcons>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Browse app icons across all apps
 */

export function useExploreIcons<TData = Awaited<ReturnType<typeof exploreIcons>>, TError = unknown>(
 params?: ExploreIconsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exploreIcons>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExploreIconsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




