/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppChangesParams,
  ChangeResource,
  CompetitorChangesParams
} from '../../models';





/**
 * @summary List store listing changes for all tracked apps
 */
export type appChangesResponse200 = {
  data: ChangeResource[]
  status: 200
}

export type appChangesResponseSuccess = (appChangesResponse200) & {
  headers: Headers;
};
;

export type appChangesResponse = (appChangesResponseSuccess)

export const getAppChangesUrl = (params?: AppChangesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/changes/apps?${stringifiedParams}` : `/api/v1/changes/apps`
}

export const appChanges = async (params?: AppChangesParams, options?: RequestInit): Promise<appChangesResponse> => {

  const res = await fetch(getAppChangesUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appChangesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appChangesResponse
}





export const getAppChangesQueryKey = (params?: AppChangesParams,) => {
    return [
    `/api/v1/changes/apps`, ...(params ? [params] : [])
    ] as const;
    }


export const getAppChangesQueryOptions = <TData = Awaited<ReturnType<typeof appChanges>>, TError = unknown>(params?: AppChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appChanges>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppChangesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appChanges>>> = ({ signal }) => appChanges(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appChanges>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppChangesQueryResult = NonNullable<Awaited<ReturnType<typeof appChanges>>>
export type AppChangesQueryError = unknown


export function useAppChanges<TData = Awaited<ReturnType<typeof appChanges>>, TError = unknown>(
 params: undefined |  AppChangesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appChanges>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appChanges>>,
          TError,
          Awaited<ReturnType<typeof appChanges>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppChanges<TData = Awaited<ReturnType<typeof appChanges>>, TError = unknown>(
 params?: AppChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appChanges>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appChanges>>,
          TError,
          Awaited<ReturnType<typeof appChanges>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppChanges<TData = Awaited<ReturnType<typeof appChanges>>, TError = unknown>(
 params?: AppChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appChanges>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List store listing changes for all tracked apps
 */

export function useAppChanges<TData = Awaited<ReturnType<typeof appChanges>>, TError = unknown>(
 params?: AppChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appChanges>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppChangesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List store listing changes for all competitor apps
 */
export type competitorChangesResponse200 = {
  data: ChangeResource[]
  status: 200
}

export type competitorChangesResponseSuccess = (competitorChangesResponse200) & {
  headers: Headers;
};
;

export type competitorChangesResponse = (competitorChangesResponseSuccess)

export const getCompetitorChangesUrl = (params?: CompetitorChangesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/changes/competitors?${stringifiedParams}` : `/api/v1/changes/competitors`
}

export const competitorChanges = async (params?: CompetitorChangesParams, options?: RequestInit): Promise<competitorChangesResponse> => {

  const res = await fetch(getCompetitorChangesUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: competitorChangesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as competitorChangesResponse
}





export const getCompetitorChangesQueryKey = (params?: CompetitorChangesParams,) => {
    return [
    `/api/v1/changes/competitors`, ...(params ? [params] : [])
    ] as const;
    }


export const getCompetitorChangesQueryOptions = <TData = Awaited<ReturnType<typeof competitorChanges>>, TError = unknown>(params?: CompetitorChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof competitorChanges>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCompetitorChangesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof competitorChanges>>> = ({ signal }) => competitorChanges(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof competitorChanges>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CompetitorChangesQueryResult = NonNullable<Awaited<ReturnType<typeof competitorChanges>>>
export type CompetitorChangesQueryError = unknown


export function useCompetitorChanges<TData = Awaited<ReturnType<typeof competitorChanges>>, TError = unknown>(
 params: undefined |  CompetitorChangesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof competitorChanges>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof competitorChanges>>,
          TError,
          Awaited<ReturnType<typeof competitorChanges>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompetitorChanges<TData = Awaited<ReturnType<typeof competitorChanges>>, TError = unknown>(
 params?: CompetitorChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof competitorChanges>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof competitorChanges>>,
          TError,
          Awaited<ReturnType<typeof competitorChanges>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompetitorChanges<TData = Awaited<ReturnType<typeof competitorChanges>>, TError = unknown>(
 params?: CompetitorChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof competitorChanges>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List store listing changes for all competitor apps
 */

export function useCompetitorChanges<TData = Awaited<ReturnType<typeof competitorChanges>>, TError = unknown>(
 params?: CompetitorChangesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof competitorChanges>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCompetitorChangesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




