/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  MessageResource,
  PasswordUpdateRequest,
  ProfileDeleteRequest,
  ProfileUpdateRequest,
  UserResource
} from '../../models';





/**
 * @summary Get authenticated user profile
 */
export type showProfileResponse200 = {
  data: UserResource
  status: 200
}

export type showProfileResponseSuccess = (showProfileResponse200) & {
  headers: Headers;
};
;

export type showProfileResponse = (showProfileResponseSuccess)

export const getShowProfileUrl = () => {




  return `/api/v1/account/profile`
}

export const showProfile = async ( options?: RequestInit): Promise<showProfileResponse> => {

  const res = await fetch(getShowProfileUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: showProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as showProfileResponse
}





export const getShowProfileQueryKey = () => {
    return [
    `/api/v1/account/profile`
    ] as const;
    }


export const getShowProfileQueryOptions = <TData = Awaited<ReturnType<typeof showProfile>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showProfile>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowProfileQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showProfile>>> = ({ signal }) => showProfile({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof showProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowProfileQueryResult = NonNullable<Awaited<ReturnType<typeof showProfile>>>
export type ShowProfileQueryError = unknown


export function useShowProfile<TData = Awaited<ReturnType<typeof showProfile>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof showProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof showProfile>>,
          TError,
          Awaited<ReturnType<typeof showProfile>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowProfile<TData = Awaited<ReturnType<typeof showProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof showProfile>>,
          TError,
          Awaited<ReturnType<typeof showProfile>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowProfile<TData = Awaited<ReturnType<typeof showProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showProfile>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get authenticated user profile
 */

export function useShowProfile<TData = Awaited<ReturnType<typeof showProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showProfile>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getShowProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Delete user account
 */
export type deleteProfileResponse204 = {
  data: void
  status: 204
}

export type deleteProfileResponseSuccess = (deleteProfileResponse204) & {
  headers: Headers;
};
;

export type deleteProfileResponse = (deleteProfileResponseSuccess)

export const getDeleteProfileUrl = () => {




  return `/api/v1/account/profile`
}

export const deleteProfile = async (profileDeleteRequest: ProfileDeleteRequest, options?: RequestInit): Promise<deleteProfileResponse> => {

  const res = await fetch(getDeleteProfileUrl(),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      profileDeleteRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteProfileResponse
}




export const getDeleteProfileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProfile>>, TError,{data: ProfileDeleteRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProfile>>, TError,{data: ProfileDeleteRequest}, TContext> => {

const mutationKey = ['deleteProfile'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProfile>>, {data: ProfileDeleteRequest}> = (props) => {
          const {data} = props ?? {};

          return  deleteProfile(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteProfileMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProfile>>>
    export type DeleteProfileMutationBody = ProfileDeleteRequest
    export type DeleteProfileMutationError = unknown

    /**
 * @summary Delete user account
 */
export const useDeleteProfile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProfile>>, TError,{data: ProfileDeleteRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProfile>>,
        TError,
        {data: ProfileDeleteRequest},
        TContext
      > => {
      return useMutation(getDeleteProfileMutationOptions(options), queryClient);
    }
    /**
 * @summary Update user profile
 */
export type updateProfileResponse200 = {
  data: UserResource
  status: 200
}

export type updateProfileResponse422 = {
  data: void
  status: 422
}

export type updateProfileResponseSuccess = (updateProfileResponse200) & {
  headers: Headers;
};
export type updateProfileResponseError = (updateProfileResponse422) & {
  headers: Headers;
};

export type updateProfileResponse = (updateProfileResponseSuccess | updateProfileResponseError)

export const getUpdateProfileUrl = () => {




  return `/api/v1/account/profile`
}

export const updateProfile = async (profileUpdateRequest: ProfileUpdateRequest, options?: RequestInit): Promise<updateProfileResponse> => {

  const res = await fetch(getUpdateProfileUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      profileUpdateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateProfileResponse
}




export const getUpdateProfileMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProfile>>, TError,{data: ProfileUpdateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateProfile>>, TError,{data: ProfileUpdateRequest}, TContext> => {

const mutationKey = ['updateProfile'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProfile>>, {data: ProfileUpdateRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateProfile(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateProfileMutationResult = NonNullable<Awaited<ReturnType<typeof updateProfile>>>
    export type UpdateProfileMutationBody = ProfileUpdateRequest
    export type UpdateProfileMutationError = void

    /**
 * @summary Update user profile
 */
export const useUpdateProfile = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProfile>>, TError,{data: ProfileUpdateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProfile>>,
        TError,
        {data: ProfileUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateProfileMutationOptions(options), queryClient);
    }
    /**
 * @summary Update user password
 */
export type updatePasswordResponse200 = {
  data: MessageResource
  status: 200
}

export type updatePasswordResponse422 = {
  data: void
  status: 422
}

export type updatePasswordResponseSuccess = (updatePasswordResponse200) & {
  headers: Headers;
};
export type updatePasswordResponseError = (updatePasswordResponse422) & {
  headers: Headers;
};

export type updatePasswordResponse = (updatePasswordResponseSuccess | updatePasswordResponseError)

export const getUpdatePasswordUrl = () => {




  return `/api/v1/account/password`
}

export const updatePassword = async (passwordUpdateRequest: PasswordUpdateRequest, options?: RequestInit): Promise<updatePasswordResponse> => {

  const res = await fetch(getUpdatePasswordUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      passwordUpdateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updatePasswordResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updatePasswordResponse
}




export const getUpdatePasswordMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: PasswordUpdateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: PasswordUpdateRequest}, TContext> => {

const mutationKey = ['updatePassword'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePassword>>, {data: PasswordUpdateRequest}> = (props) => {
          const {data} = props ?? {};

          return  updatePassword(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof updatePassword>>>
    export type UpdatePasswordMutationBody = PasswordUpdateRequest
    export type UpdatePasswordMutationError = void

    /**
 * @summary Update user password
 */
export const useUpdatePassword = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: PasswordUpdateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePassword>>,
        TError,
        {data: PasswordUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdatePasswordMutationOptions(options), queryClient);
    }
