/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppDetailResource,
  AppKeywordsParams,
  AppResource,
  AppReviewsParams,
  AppReviewsSummary200,
  AppReviewsSummaryParams,
  AppSearchResultResource,
  BuildStatusResource,
  CompareKeywordsParams,
  CompetitorResource,
  KeywordCompareResource,
  KeywordDensityResource,
  ListAppsParams,
  ReviewResource,
  SearchAppsParams,
  StoreAppRequest,
  StoreCompetitorRequest
} from '../../models';





/**
 * @summary List tracked apps
 */
export type listAppsResponse200 = {
  data: AppResource[]
  status: 200
}

export type listAppsResponseSuccess = (listAppsResponse200) & {
  headers: Headers;
};
;

export type listAppsResponse = (listAppsResponseSuccess)

export const getListAppsUrl = (params?: ListAppsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/apps?${stringifiedParams}` : `/api/v1/apps`
}

export const listApps = async (params?: ListAppsParams, options?: RequestInit): Promise<listAppsResponse> => {

  const res = await fetch(getListAppsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listAppsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listAppsResponse
}





export const getListAppsQueryKey = (params?: ListAppsParams,) => {
    return [
    `/api/v1/apps`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAppsQueryOptions = <TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(params?: ListAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAppsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listApps>>> = ({ signal }) => listApps(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAppsQueryResult = NonNullable<Awaited<ReturnType<typeof listApps>>>
export type ListAppsQueryError = unknown


export function useListApps<TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(
 params: undefined |  ListAppsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listApps>>,
          TError,
          Awaited<ReturnType<typeof listApps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListApps<TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(
 params?: ListAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listApps>>,
          TError,
          Awaited<ReturnType<typeof listApps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListApps<TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(
 params?: ListAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List tracked apps
 */

export function useListApps<TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(
 params?: ListAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAppsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Register and track an app
 */
export type storeAppResponse201 = {
  data: AppDetailResource
  status: 201
}

export type storeAppResponse422 = {
  data: void
  status: 422
}

export type storeAppResponseSuccess = (storeAppResponse201) & {
  headers: Headers;
};
export type storeAppResponseError = (storeAppResponse422) & {
  headers: Headers;
};

export type storeAppResponse = (storeAppResponseSuccess | storeAppResponseError)

export const getStoreAppUrl = () => {




  return `/api/v1/apps`
}

export const storeApp = async (storeAppRequest: StoreAppRequest, options?: RequestInit): Promise<storeAppResponse> => {

  const res = await fetch(getStoreAppUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeAppRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: storeAppResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as storeAppResponse
}




export const getStoreAppMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeApp>>, TError,{data: StoreAppRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof storeApp>>, TError,{data: StoreAppRequest}, TContext> => {

const mutationKey = ['storeApp'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storeApp>>, {data: StoreAppRequest}> = (props) => {
          const {data} = props ?? {};

          return  storeApp(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StoreAppMutationResult = NonNullable<Awaited<ReturnType<typeof storeApp>>>
    export type StoreAppMutationBody = StoreAppRequest
    export type StoreAppMutationError = void

    /**
 * @summary Register and track an app
 */
export const useStoreApp = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeApp>>, TError,{data: StoreAppRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof storeApp>>,
        TError,
        {data: StoreAppRequest},
        TContext
      > => {
      return useMutation(getStoreAppMutationOptions(options), queryClient);
    }
    /**
 * @summary Get app details (creates and builds DNA if first visit)
 */
export type showAppResponse200 = {
  data: AppDetailResource
  status: 200
}

export type showAppResponseSuccess = (showAppResponse200) & {
  headers: Headers;
};
;

export type showAppResponse = (showAppResponseSuccess)

export const getShowAppUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/apps/${platform}/${externalId}`
}

export const showApp = async (platform: 'ios' | 'android',
    externalId: string, options?: RequestInit): Promise<showAppResponse> => {

  const res = await fetch(getShowAppUrl(platform,externalId),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: showAppResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as showAppResponse
}





export const getShowAppQueryKey = (platform: 'ios' | 'android',
    externalId: string,) => {
    return [
    `/api/v1/apps/${platform}/${externalId}`
    ] as const;
    }


export const getShowAppQueryOptions = <TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowAppQueryKey(platform,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showApp>>> = ({ signal }) => showApp(platform,externalId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowAppQueryResult = NonNullable<Awaited<ReturnType<typeof showApp>>>
export type ShowAppQueryError = unknown


export function useShowApp<TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof showApp>>,
          TError,
          Awaited<ReturnType<typeof showApp>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowApp<TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof showApp>>,
          TError,
          Awaited<ReturnType<typeof showApp>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowApp<TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get app details (creates and builds DNA if first visit)
 */

export function useShowApp<TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getShowAppQueryOptions(platform,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Rebuild app DNA
 */
export type rebuildAppResponse200 = {
  data: AppDetailResource
  status: 200
}

export type rebuildAppResponse404 = {
  data: void
  status: 404
}

export type rebuildAppResponseSuccess = (rebuildAppResponse200) & {
  headers: Headers;
};
export type rebuildAppResponseError = (rebuildAppResponse404) & {
  headers: Headers;
};

export type rebuildAppResponse = (rebuildAppResponseSuccess | rebuildAppResponseError)

export const getRebuildAppUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/apps/${platform}/${externalId}/rebuild`
}

export const rebuildApp = async (platform: 'ios' | 'android',
    externalId: string, options?: RequestInit): Promise<rebuildAppResponse> => {

  const res = await fetch(getRebuildAppUrl(platform,externalId),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rebuildAppResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as rebuildAppResponse
}




export const getRebuildAppMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rebuildApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof rebuildApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext> => {

const mutationKey = ['rebuildApp'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rebuildApp>>, {platform: 'ios' | 'android';externalId: string}> = (props) => {
          const {platform,externalId} = props ?? {};

          return  rebuildApp(platform,externalId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RebuildAppMutationResult = NonNullable<Awaited<ReturnType<typeof rebuildApp>>>

    export type RebuildAppMutationError = void

    /**
 * @summary Rebuild app DNA
 */
export const useRebuildApp = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rebuildApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rebuildApp>>,
        TError,
        {platform: 'ios' | 'android';externalId: string},
        TContext
      > => {
      return useMutation(getRebuildAppMutationOptions(options), queryClient);
    }
    /**
 * @summary Track an app (adds to daily refresh)
 */
export type trackAppResponse204 = {
  data: void
  status: 204
}

export type trackAppResponseSuccess = (trackAppResponse204) & {
  headers: Headers;
};
;

export type trackAppResponse = (trackAppResponseSuccess)

export const getTrackAppUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/apps/${platform}/${externalId}/track`
}

export const trackApp = async (platform: 'ios' | 'android',
    externalId: string, options?: RequestInit): Promise<trackAppResponse> => {

  const res = await fetch(getTrackAppUrl(platform,externalId),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: trackAppResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as trackAppResponse
}




export const getTrackAppMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof trackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext> => {

const mutationKey = ['trackApp'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof trackApp>>, {platform: 'ios' | 'android';externalId: string}> = (props) => {
          const {platform,externalId} = props ?? {};

          return  trackApp(platform,externalId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TrackAppMutationResult = NonNullable<Awaited<ReturnType<typeof trackApp>>>

    export type TrackAppMutationError = unknown

    /**
 * @summary Track an app (adds to daily refresh)
 */
export const useTrackApp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof trackApp>>,
        TError,
        {platform: 'ios' | 'android';externalId: string},
        TContext
      > => {
      return useMutation(getTrackAppMutationOptions(options), queryClient);
    }
    /**
 * @summary Untrack an app (removes from daily refresh)
 */
export type untrackAppResponse204 = {
  data: void
  status: 204
}

export type untrackAppResponseSuccess = (untrackAppResponse204) & {
  headers: Headers;
};
;

export type untrackAppResponse = (untrackAppResponseSuccess)

export const getUntrackAppUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/apps/${platform}/${externalId}/track`
}

export const untrackApp = async (platform: 'ios' | 'android',
    externalId: string, options?: RequestInit): Promise<untrackAppResponse> => {

  const res = await fetch(getUntrackAppUrl(platform,externalId),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: untrackAppResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as untrackAppResponse
}




export const getUntrackAppMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof untrackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof untrackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext> => {

const mutationKey = ['untrackApp'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof untrackApp>>, {platform: 'ios' | 'android';externalId: string}> = (props) => {
          const {platform,externalId} = props ?? {};

          return  untrackApp(platform,externalId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UntrackAppMutationResult = NonNullable<Awaited<ReturnType<typeof untrackApp>>>

    export type UntrackAppMutationError = unknown

    /**
 * @summary Untrack an app (removes from daily refresh)
 */
export const useUntrackApp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof untrackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof untrackApp>>,
        TError,
        {platform: 'ios' | 'android';externalId: string},
        TContext
      > => {
      return useMutation(getUntrackAppMutationOptions(options), queryClient);
    }
    /**
 * @summary Search apps in stores
 */
export type searchAppsResponse200 = {
  data: AppSearchResultResource[]
  status: 200
}

export type searchAppsResponseSuccess = (searchAppsResponse200) & {
  headers: Headers;
};
;

export type searchAppsResponse = (searchAppsResponseSuccess)

export const getSearchAppsUrl = (params: SearchAppsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/apps/search?${stringifiedParams}` : `/api/v1/apps/search`
}

export const searchApps = async (params: SearchAppsParams, options?: RequestInit): Promise<searchAppsResponse> => {

  const res = await fetch(getSearchAppsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchAppsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchAppsResponse
}





export const getSearchAppsQueryKey = (params?: SearchAppsParams,) => {
    return [
    `/api/v1/apps/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchAppsQueryOptions = <TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(params: SearchAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchAppsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchApps>>> = ({ signal }) => searchApps(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchAppsQueryResult = NonNullable<Awaited<ReturnType<typeof searchApps>>>
export type SearchAppsQueryError = unknown


export function useSearchApps<TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(
 params: SearchAppsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchApps>>,
          TError,
          Awaited<ReturnType<typeof searchApps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchApps<TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(
 params: SearchAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchApps>>,
          TError,
          Awaited<ReturnType<typeof searchApps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchApps<TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(
 params: SearchAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search apps in stores
 */

export function useSearchApps<TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(
 params: SearchAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchAppsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get app build status
 */
export type appBuildStatusResponse200 = {
  data: BuildStatusResource
  status: 200
}

export type appBuildStatusResponse404 = {
  data: void
  status: 404
}

export type appBuildStatusResponseSuccess = (appBuildStatusResponse200) & {
  headers: Headers;
};
export type appBuildStatusResponseError = (appBuildStatusResponse404) & {
  headers: Headers;
};

export type appBuildStatusResponse = (appBuildStatusResponseSuccess | appBuildStatusResponseError)

export const getAppBuildStatusUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/apps/${platform}/${externalId}/build-status`
}

export const appBuildStatus = async (platform: 'ios' | 'android',
    externalId: string, options?: RequestInit): Promise<appBuildStatusResponse> => {

  const res = await fetch(getAppBuildStatusUrl(platform,externalId),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appBuildStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appBuildStatusResponse
}





export const getAppBuildStatusQueryKey = (platform: 'ios' | 'android',
    externalId: string,) => {
    return [
    `/api/v1/apps/${platform}/${externalId}/build-status`
    ] as const;
    }


export const getAppBuildStatusQueryOptions = <TData = Awaited<ReturnType<typeof appBuildStatus>>, TError = void>(platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appBuildStatus>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppBuildStatusQueryKey(platform,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appBuildStatus>>> = ({ signal }) => appBuildStatus(platform,externalId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appBuildStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppBuildStatusQueryResult = NonNullable<Awaited<ReturnType<typeof appBuildStatus>>>
export type AppBuildStatusQueryError = void


export function useAppBuildStatus<TData = Awaited<ReturnType<typeof appBuildStatus>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appBuildStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appBuildStatus>>,
          TError,
          Awaited<ReturnType<typeof appBuildStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppBuildStatus<TData = Awaited<ReturnType<typeof appBuildStatus>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appBuildStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appBuildStatus>>,
          TError,
          Awaited<ReturnType<typeof appBuildStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppBuildStatus<TData = Awaited<ReturnType<typeof appBuildStatus>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appBuildStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get app build status
 */

export function useAppBuildStatus<TData = Awaited<ReturnType<typeof appBuildStatus>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appBuildStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppBuildStatusQueryOptions(platform,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List competitors for an app
 */
export type listCompetitorsResponse200 = {
  data: CompetitorResource[]
  status: 200
}

export type listCompetitorsResponse404 = {
  data: void
  status: 404
}

export type listCompetitorsResponseSuccess = (listCompetitorsResponse200) & {
  headers: Headers;
};
export type listCompetitorsResponseError = (listCompetitorsResponse404) & {
  headers: Headers;
};

export type listCompetitorsResponse = (listCompetitorsResponseSuccess | listCompetitorsResponseError)

export const getListCompetitorsUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/apps/${platform}/${externalId}/competitors`
}

export const listCompetitors = async (platform: 'ios' | 'android',
    externalId: string, options?: RequestInit): Promise<listCompetitorsResponse> => {

  const res = await fetch(getListCompetitorsUrl(platform,externalId),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listCompetitorsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listCompetitorsResponse
}





export const getListCompetitorsQueryKey = (platform: 'ios' | 'android',
    externalId: string,) => {
    return [
    `/api/v1/apps/${platform}/${externalId}/competitors`
    ] as const;
    }


export const getListCompetitorsQueryOptions = <TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCompetitorsQueryKey(platform,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCompetitors>>> = ({ signal }) => listCompetitors(platform,externalId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCompetitorsQueryResult = NonNullable<Awaited<ReturnType<typeof listCompetitors>>>
export type ListCompetitorsQueryError = void


export function useListCompetitors<TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCompetitors>>,
          TError,
          Awaited<ReturnType<typeof listCompetitors>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCompetitors<TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCompetitors>>,
          TError,
          Awaited<ReturnType<typeof listCompetitors>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCompetitors<TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List competitors for an app
 */

export function useListCompetitors<TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCompetitorsQueryOptions(platform,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Add a competitor to an app
 */
export type storeCompetitorResponse201 = {
  data: CompetitorResource
  status: 201
}

export type storeCompetitorResponse404 = {
  data: void
  status: 404
}

export type storeCompetitorResponse422 = {
  data: void
  status: 422
}

export type storeCompetitorResponseSuccess = (storeCompetitorResponse201) & {
  headers: Headers;
};
export type storeCompetitorResponseError = (storeCompetitorResponse404 | storeCompetitorResponse422) & {
  headers: Headers;
};

export type storeCompetitorResponse = (storeCompetitorResponseSuccess | storeCompetitorResponseError)

export const getStoreCompetitorUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/apps/${platform}/${externalId}/competitors`
}

export const storeCompetitor = async (platform: 'ios' | 'android',
    externalId: string,
    storeCompetitorRequest: StoreCompetitorRequest, options?: RequestInit): Promise<storeCompetitorResponse> => {

  const res = await fetch(getStoreCompetitorUrl(platform,externalId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeCompetitorRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: storeCompetitorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as storeCompetitorResponse
}




export const getStoreCompetitorMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof storeCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest}, TContext> => {

const mutationKey = ['storeCompetitor'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storeCompetitor>>, {platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest}> = (props) => {
          const {platform,externalId,data} = props ?? {};

          return  storeCompetitor(platform,externalId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StoreCompetitorMutationResult = NonNullable<Awaited<ReturnType<typeof storeCompetitor>>>
    export type StoreCompetitorMutationBody = StoreCompetitorRequest
    export type StoreCompetitorMutationError = void

    /**
 * @summary Add a competitor to an app
 */
export const useStoreCompetitor = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof storeCompetitor>>,
        TError,
        {platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest},
        TContext
      > => {
      return useMutation(getStoreCompetitorMutationOptions(options), queryClient);
    }
    /**
 * @summary List all competitor apps across all user apps
 */
export type listAllCompetitorsResponse200 = {
  data: AppResource[]
  status: 200
}

export type listAllCompetitorsResponseSuccess = (listAllCompetitorsResponse200) & {
  headers: Headers;
};
;

export type listAllCompetitorsResponse = (listAllCompetitorsResponseSuccess)

export const getListAllCompetitorsUrl = () => {




  return `/api/v1/competitors`
}

export const listAllCompetitors = async ( options?: RequestInit): Promise<listAllCompetitorsResponse> => {

  const res = await fetch(getListAllCompetitorsUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listAllCompetitorsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listAllCompetitorsResponse
}





export const getListAllCompetitorsQueryKey = () => {
    return [
    `/api/v1/competitors`
    ] as const;
    }


export const getListAllCompetitorsQueryOptions = <TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAllCompetitorsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllCompetitors>>> = ({ signal }) => listAllCompetitors({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAllCompetitorsQueryResult = NonNullable<Awaited<ReturnType<typeof listAllCompetitors>>>
export type ListAllCompetitorsQueryError = unknown


export function useListAllCompetitors<TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllCompetitors>>,
          TError,
          Awaited<ReturnType<typeof listAllCompetitors>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAllCompetitors<TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllCompetitors>>,
          TError,
          Awaited<ReturnType<typeof listAllCompetitors>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAllCompetitors<TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all competitor apps across all user apps
 */

export function useListAllCompetitors<TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAllCompetitorsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Remove a competitor from an app
 */
export type deleteCompetitorResponse204 = {
  data: void
  status: 204
}

export type deleteCompetitorResponse404 = {
  data: void
  status: 404
}

export type deleteCompetitorResponseSuccess = (deleteCompetitorResponse204) & {
  headers: Headers;
};
export type deleteCompetitorResponseError = (deleteCompetitorResponse404) & {
  headers: Headers;
};

export type deleteCompetitorResponse = (deleteCompetitorResponseSuccess | deleteCompetitorResponseError)

export const getDeleteCompetitorUrl = (platform: 'ios' | 'android',
    externalId: string,
    competitor: number,) => {




  return `/api/v1/apps/${platform}/${externalId}/competitors/${competitor}`
}

export const deleteCompetitor = async (platform: 'ios' | 'android',
    externalId: string,
    competitor: number, options?: RequestInit): Promise<deleteCompetitorResponse> => {

  const res = await fetch(getDeleteCompetitorUrl(platform,externalId,competitor),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteCompetitorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteCompetitorResponse
}




export const getDeleteCompetitorMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;competitor: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;competitor: number}, TContext> => {

const mutationKey = ['deleteCompetitor'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCompetitor>>, {platform: 'ios' | 'android';externalId: string;competitor: number}> = (props) => {
          const {platform,externalId,competitor} = props ?? {};

          return  deleteCompetitor(platform,externalId,competitor,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCompetitorMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCompetitor>>>

    export type DeleteCompetitorMutationError = void

    /**
 * @summary Remove a competitor from an app
 */
export const useDeleteCompetitor = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;competitor: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCompetitor>>,
        TError,
        {platform: 'ios' | 'android';externalId: string;competitor: number},
        TContext
      > => {
      return useMutation(getDeleteCompetitorMutationOptions(options), queryClient);
    }
    /**
 * @summary Get keyword density for an app
 */
export type appKeywordsResponse200 = {
  data: KeywordDensityResource[]
  status: 200
}

export type appKeywordsResponse404 = {
  data: void
  status: 404
}

export type appKeywordsResponseSuccess = (appKeywordsResponse200) & {
  headers: Headers;
};
export type appKeywordsResponseError = (appKeywordsResponse404) & {
  headers: Headers;
};

export type appKeywordsResponse = (appKeywordsResponseSuccess | appKeywordsResponseError)

export const getAppKeywordsUrl = (platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/apps/${platform}/${externalId}/keywords?${stringifiedParams}` : `/api/v1/apps/${platform}/${externalId}/keywords`
}

export const appKeywords = async (platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams, options?: RequestInit): Promise<appKeywordsResponse> => {

  const res = await fetch(getAppKeywordsUrl(platform,externalId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appKeywordsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appKeywordsResponse
}





export const getAppKeywordsQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams,) => {
    return [
    `/api/v1/apps/${platform}/${externalId}/keywords`, ...(params ? [params] : [])
    ] as const;
    }


export const getAppKeywordsQueryOptions = <TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppKeywordsQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appKeywords>>> = ({ signal }) => appKeywords(platform,externalId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppKeywordsQueryResult = NonNullable<Awaited<ReturnType<typeof appKeywords>>>
export type AppKeywordsQueryError = void


export function useAppKeywords<TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: undefined |  AppKeywordsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appKeywords>>,
          TError,
          Awaited<ReturnType<typeof appKeywords>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppKeywords<TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appKeywords>>,
          TError,
          Awaited<ReturnType<typeof appKeywords>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppKeywords<TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get keyword density for an app
 */

export function useAppKeywords<TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppKeywordsQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Compare keyword density with other apps
 */
export type compareKeywordsResponse200 = {
  data: KeywordCompareResource
  status: 200
}

export type compareKeywordsResponse404 = {
  data: void
  status: 404
}

export type compareKeywordsResponseSuccess = (compareKeywordsResponse200) & {
  headers: Headers;
};
export type compareKeywordsResponseError = (compareKeywordsResponse404) & {
  headers: Headers;
};

export type compareKeywordsResponse = (compareKeywordsResponseSuccess | compareKeywordsResponseError)

export const getCompareKeywordsUrl = (platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/apps/${platform}/${externalId}/keywords/compare?${stringifiedParams}` : `/api/v1/apps/${platform}/${externalId}/keywords/compare`
}

export const compareKeywords = async (platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options?: RequestInit): Promise<compareKeywordsResponse> => {

  const res = await fetch(getCompareKeywordsUrl(platform,externalId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: compareKeywordsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as compareKeywordsResponse
}





export const getCompareKeywordsQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: CompareKeywordsParams,) => {
    return [
    `/api/v1/apps/${platform}/${externalId}/keywords/compare`, ...(params ? [params] : [])
    ] as const;
    }


export const getCompareKeywordsQueryOptions = <TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCompareKeywordsQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof compareKeywords>>> = ({ signal }) => compareKeywords(platform,externalId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CompareKeywordsQueryResult = NonNullable<Awaited<ReturnType<typeof compareKeywords>>>
export type CompareKeywordsQueryError = void


export function useCompareKeywords<TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof compareKeywords>>,
          TError,
          Awaited<ReturnType<typeof compareKeywords>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompareKeywords<TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof compareKeywords>>,
          TError,
          Awaited<ReturnType<typeof compareKeywords>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompareKeywords<TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Compare keyword density with other apps
 */

export function useCompareKeywords<TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCompareKeywordsQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List reviews for an app
 */
export type appReviewsResponse200 = {
  data: ReviewResource[]
  status: 200
}

export type appReviewsResponse404 = {
  data: void
  status: 404
}

export type appReviewsResponseSuccess = (appReviewsResponse200) & {
  headers: Headers;
};
export type appReviewsResponseError = (appReviewsResponse404) & {
  headers: Headers;
};

export type appReviewsResponse = (appReviewsResponseSuccess | appReviewsResponseError)

export const getAppReviewsUrl = (platform: 'ios' | 'android',
    externalId: string,
    params?: AppReviewsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/apps/${platform}/${externalId}/reviews?${stringifiedParams}` : `/api/v1/apps/${platform}/${externalId}/reviews`
}

export const appReviews = async (platform: 'ios' | 'android',
    externalId: string,
    params?: AppReviewsParams, options?: RequestInit): Promise<appReviewsResponse> => {

  const res = await fetch(getAppReviewsUrl(platform,externalId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appReviewsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appReviewsResponse
}





export const getAppReviewsQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: AppReviewsParams,) => {
    return [
    `/api/v1/apps/${platform}/${externalId}/reviews`, ...(params ? [params] : [])
    ] as const;
    }


export const getAppReviewsQueryOptions = <TData = Awaited<ReturnType<typeof appReviews>>, TError = void>(platform: 'ios' | 'android',
    externalId: string,
    params?: AppReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appReviews>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppReviewsQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appReviews>>> = ({ signal }) => appReviews(platform,externalId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appReviews>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppReviewsQueryResult = NonNullable<Awaited<ReturnType<typeof appReviews>>>
export type AppReviewsQueryError = void


export function useAppReviews<TData = Awaited<ReturnType<typeof appReviews>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: undefined |  AppReviewsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appReviews>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appReviews>>,
          TError,
          Awaited<ReturnType<typeof appReviews>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppReviews<TData = Awaited<ReturnType<typeof appReviews>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appReviews>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appReviews>>,
          TError,
          Awaited<ReturnType<typeof appReviews>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppReviews<TData = Awaited<ReturnType<typeof appReviews>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appReviews>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List reviews for an app
 */

export function useAppReviews<TData = Awaited<ReturnType<typeof appReviews>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appReviews>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppReviewsQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get review summary and rating distribution for an app
 */
export type appReviewsSummaryResponse200 = {
  data: AppReviewsSummary200
  status: 200
}

export type appReviewsSummaryResponse404 = {
  data: void
  status: 404
}

export type appReviewsSummaryResponseSuccess = (appReviewsSummaryResponse200) & {
  headers: Headers;
};
export type appReviewsSummaryResponseError = (appReviewsSummaryResponse404) & {
  headers: Headers;
};

export type appReviewsSummaryResponse = (appReviewsSummaryResponseSuccess | appReviewsSummaryResponseError)

export const getAppReviewsSummaryUrl = (platform: 'ios' | 'android',
    externalId: string,
    params?: AppReviewsSummaryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/apps/${platform}/${externalId}/reviews/summary?${stringifiedParams}` : `/api/v1/apps/${platform}/${externalId}/reviews/summary`
}

export const appReviewsSummary = async (platform: 'ios' | 'android',
    externalId: string,
    params?: AppReviewsSummaryParams, options?: RequestInit): Promise<appReviewsSummaryResponse> => {

  const res = await fetch(getAppReviewsSummaryUrl(platform,externalId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appReviewsSummaryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appReviewsSummaryResponse
}





export const getAppReviewsSummaryQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: AppReviewsSummaryParams,) => {
    return [
    `/api/v1/apps/${platform}/${externalId}/reviews/summary`, ...(params ? [params] : [])
    ] as const;
    }


export const getAppReviewsSummaryQueryOptions = <TData = Awaited<ReturnType<typeof appReviewsSummary>>, TError = void>(platform: 'ios' | 'android',
    externalId: string,
    params?: AppReviewsSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appReviewsSummary>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppReviewsSummaryQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appReviewsSummary>>> = ({ signal }) => appReviewsSummary(platform,externalId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appReviewsSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppReviewsSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof appReviewsSummary>>>
export type AppReviewsSummaryQueryError = void


export function useAppReviewsSummary<TData = Awaited<ReturnType<typeof appReviewsSummary>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: undefined |  AppReviewsSummaryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appReviewsSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appReviewsSummary>>,
          TError,
          Awaited<ReturnType<typeof appReviewsSummary>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppReviewsSummary<TData = Awaited<ReturnType<typeof appReviewsSummary>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppReviewsSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appReviewsSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appReviewsSummary>>,
          TError,
          Awaited<ReturnType<typeof appReviewsSummary>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppReviewsSummary<TData = Awaited<ReturnType<typeof appReviewsSummary>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppReviewsSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appReviewsSummary>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get review summary and rating distribution for an app
 */

export function useAppReviewsSummary<TData = Awaited<ReturnType<typeof appReviewsSummary>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppReviewsSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appReviewsSummary>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppReviewsSummaryQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




