/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { AppReviewsRating } from './appReviewsRating';
import type { AppReviewsSort } from './appReviewsSort';

export type AppReviewsParams = {
country_code?: string;
rating?: AppReviewsRating;
sort?: AppReviewsSort;
per_page?: number;
page?: number;
};
