/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { AppReviewsSummary200Distribution } from './appReviewsSummary200Distribution';

export type AppReviewsSummary200 = {
  total_reviews?: number;
  average_rating?: number;
  distribution?: AppReviewsSummary200Distribution;
  countries?: string[];
};
