/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { BuildStatus } from './buildStatus';
import type { Platform } from './platform';
import type { Publisher } from './publisher';
import type { StoreCategory } from './storeCategory';

export interface AppResource {
  id: number;
  name: string;
  platform: Platform;
  external_id: string;
  publisher?: Publisher | null;
  category?: StoreCategory | null;
  build_status: BuildStatus;
  /** @nullable */
  icon_url?: string | null;
  /** @nullable */
  rating?: number | null;
  /** @nullable */
  rating_count?: number | null;
  /** @nullable */
  version?: string | null;
  /** @nullable */
  last_build_at?: string | null;
  created_at: string;
}
