/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

export type ReviewIndexRequestSort = typeof ReviewIndexRequestSort[keyof typeof ReviewIndexRequestSort];


export const ReviewIndexRequestSort = {
  latest: 'latest',
  oldest: 'oldest',
  highest: 'highest',
  lowest: 'lowest',
} as const;
