/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppDetailResource,
  AppKeywordsParams,
  AppListingParams,
  AppRankingResource,
  AppResource,
  CompareKeywordsParams,
  CompetitorGroupResource,
  CompetitorResource,
  KeywordCompareResource,
  KeywordDensityResource,
  ListAppRankingsParams,
  ListAppsParams,
  ListingResource,
  SearchAppsParams,
  StoreAppRequest,
  StoreCompetitorRequest,
  SyncStatusResource
} from '../../models';





/**
 * @summary List tracked apps
 */
export type listAppsResponse200 = {
  data: AppResource[]
  status: 200
}

export type listAppsResponseSuccess = (listAppsResponse200) & {
  headers: Headers;
};
;

export type listAppsResponse = (listAppsResponseSuccess)

export const getListAppsUrl = (params?: ListAppsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/apps?${stringifiedParams}` : `/api/v1/apps`
}

export const listApps = async (params?: ListAppsParams, options?: RequestInit): Promise<listAppsResponse> => {

  const res = await fetch(getListAppsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listAppsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listAppsResponse
}





export const getListAppsQueryKey = (params?: ListAppsParams,) => {
    return [
    `/api/v1/apps`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAppsQueryOptions = <TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(params?: ListAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAppsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listApps>>> = ({ signal }) => listApps(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAppsQueryResult = NonNullable<Awaited<ReturnType<typeof listApps>>>
export type ListAppsQueryError = unknown


export function useListApps<TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(
 params: undefined |  ListAppsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listApps>>,
          TError,
          Awaited<ReturnType<typeof listApps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListApps<TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(
 params?: ListAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listApps>>,
          TError,
          Awaited<ReturnType<typeof listApps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListApps<TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(
 params?: ListAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List tracked apps
 */

export function useListApps<TData = Awaited<ReturnType<typeof listApps>>, TError = unknown>(
 params?: ListAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listApps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAppsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Register and track an app
 */
export type storeAppResponse201 = {
  data: AppDetailResource
  status: 201
}

export type storeAppResponse422 = {
  data: void
  status: 422
}

export type storeAppResponseSuccess = (storeAppResponse201) & {
  headers: Headers;
};
export type storeAppResponseError = (storeAppResponse422) & {
  headers: Headers;
};

export type storeAppResponse = (storeAppResponseSuccess | storeAppResponseError)

export const getStoreAppUrl = () => {




  return `/api/v1/apps`
}

export const storeApp = async (storeAppRequest: StoreAppRequest, options?: RequestInit): Promise<storeAppResponse> => {

  const res = await fetch(getStoreAppUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeAppRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: storeAppResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as storeAppResponse
}




export const getStoreAppMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeApp>>, TError,{data: StoreAppRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof storeApp>>, TError,{data: StoreAppRequest}, TContext> => {

const mutationKey = ['storeApp'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storeApp>>, {data: StoreAppRequest}> = (props) => {
          const {data} = props ?? {};

          return  storeApp(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StoreAppMutationResult = NonNullable<Awaited<ReturnType<typeof storeApp>>>
    export type StoreAppMutationBody = StoreAppRequest
    export type StoreAppMutationError = void

    /**
 * @summary Register and track an app
 */
export const useStoreApp = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeApp>>, TError,{data: StoreAppRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof storeApp>>,
        TError,
        {data: StoreAppRequest},
        TContext
      > => {
      return useMutation(getStoreAppMutationOptions(options), queryClient);
    }
    /**
 * @summary Get app details
 */
export type showAppResponse200 = {
  data: AppDetailResource
  status: 200
}

export type showAppResponseSuccess = (showAppResponse200) & {
  headers: Headers;
};
;

export type showAppResponse = (showAppResponseSuccess)

export const getShowAppUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/apps/${platform}/${externalId}`
}

export const showApp = async (platform: 'ios' | 'android',
    externalId: string, options?: RequestInit): Promise<showAppResponse> => {

  const res = await fetch(getShowAppUrl(platform,externalId),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: showAppResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as showAppResponse
}





export const getShowAppQueryKey = (platform: 'ios' | 'android',
    externalId: string,) => {
    return [
    `/api/v1/apps/${platform}/${externalId}`
    ] as const;
    }


export const getShowAppQueryOptions = <TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowAppQueryKey(platform,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showApp>>> = ({ signal }) => showApp(platform,externalId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowAppQueryResult = NonNullable<Awaited<ReturnType<typeof showApp>>>
export type ShowAppQueryError = unknown


export function useShowApp<TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof showApp>>,
          TError,
          Awaited<ReturnType<typeof showApp>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowApp<TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof showApp>>,
          TError,
          Awaited<ReturnType<typeof showApp>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowApp<TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get app details
 */

export function useShowApp<TData = Awaited<ReturnType<typeof showApp>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showApp>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getShowAppQueryOptions(platform,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get store listing for a specific country
 */
export type appListingResponse200 = {
  data: ListingResource
  status: 200
}

export type appListingResponseSuccess = (appListingResponse200) & {
  headers: Headers;
};
;

export type appListingResponse = (appListingResponseSuccess)

export const getAppListingUrl = (platform: 'ios' | 'android',
    externalId: string,
    params: AppListingParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/apps/${platform}/${externalId}/listing?${stringifiedParams}` : `/api/v1/apps/${platform}/${externalId}/listing`
}

export const appListing = async (platform: 'ios' | 'android',
    externalId: string,
    params: AppListingParams, options?: RequestInit): Promise<appListingResponse> => {

  const res = await fetch(getAppListingUrl(platform,externalId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appListingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appListingResponse
}





export const getAppListingQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: AppListingParams,) => {
    return [
    `/api/v1/apps/${platform}/${externalId}/listing`, ...(params ? [params] : [])
    ] as const;
    }


export const getAppListingQueryOptions = <TData = Awaited<ReturnType<typeof appListing>>, TError = unknown>(platform: 'ios' | 'android',
    externalId: string,
    params: AppListingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appListing>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppListingQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appListing>>> = ({ signal }) => appListing(platform,externalId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appListing>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppListingQueryResult = NonNullable<Awaited<ReturnType<typeof appListing>>>
export type AppListingQueryError = unknown


export function useAppListing<TData = Awaited<ReturnType<typeof appListing>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params: AppListingParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appListing>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appListing>>,
          TError,
          Awaited<ReturnType<typeof appListing>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppListing<TData = Awaited<ReturnType<typeof appListing>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params: AppListingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appListing>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appListing>>,
          TError,
          Awaited<ReturnType<typeof appListing>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppListing<TData = Awaited<ReturnType<typeof appListing>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params: AppListingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appListing>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get store listing for a specific country
 */

export function useAppListing<TData = Awaited<ReturnType<typeof appListing>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params: AppListingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appListing>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppListingQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Trigger a sync job for this app
 */
export type syncAppResponse200 = {
  data: SyncStatusResource
  status: 200
}

export type syncAppResponseSuccess = (syncAppResponse200) & {
  headers: Headers;
};
;

export type syncAppResponse = (syncAppResponseSuccess)

export const getSyncAppUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/apps/${platform}/${externalId}/sync`
}

export const syncApp = async (platform: 'ios' | 'android',
    externalId: string, options?: RequestInit): Promise<syncAppResponse> => {

  const res = await fetch(getSyncAppUrl(platform,externalId),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: syncAppResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as syncAppResponse
}




export const getSyncAppMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof syncApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext> => {

const mutationKey = ['syncApp'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncApp>>, {platform: 'ios' | 'android';externalId: string}> = (props) => {
          const {platform,externalId} = props ?? {};

          return  syncApp(platform,externalId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SyncAppMutationResult = NonNullable<Awaited<ReturnType<typeof syncApp>>>

    export type SyncAppMutationError = unknown

    /**
 * @summary Trigger a sync job for this app
 */
export const useSyncApp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncApp>>,
        TError,
        {platform: 'ios' | 'android';externalId: string},
        TContext
      > => {
      return useMutation(getSyncAppMutationOptions(options), queryClient);
    }
    /**
 * @summary Get current sync status for this app
 */
export type appSyncStatusResponse200 = {
  data: SyncStatusResource
  status: 200
}

export type appSyncStatusResponseSuccess = (appSyncStatusResponse200) & {
  headers: Headers;
};
;

export type appSyncStatusResponse = (appSyncStatusResponseSuccess)

export const getAppSyncStatusUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/apps/${platform}/${externalId}/sync-status`
}

export const appSyncStatus = async (platform: 'ios' | 'android',
    externalId: string, options?: RequestInit): Promise<appSyncStatusResponse> => {

  const res = await fetch(getAppSyncStatusUrl(platform,externalId),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appSyncStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appSyncStatusResponse
}





export const getAppSyncStatusQueryKey = (platform: 'ios' | 'android',
    externalId: string,) => {
    return [
    `/api/v1/apps/${platform}/${externalId}/sync-status`
    ] as const;
    }


export const getAppSyncStatusQueryOptions = <TData = Awaited<ReturnType<typeof appSyncStatus>>, TError = unknown>(platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appSyncStatus>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppSyncStatusQueryKey(platform,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appSyncStatus>>> = ({ signal }) => appSyncStatus(platform,externalId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appSyncStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppSyncStatusQueryResult = NonNullable<Awaited<ReturnType<typeof appSyncStatus>>>
export type AppSyncStatusQueryError = unknown


export function useAppSyncStatus<TData = Awaited<ReturnType<typeof appSyncStatus>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appSyncStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appSyncStatus>>,
          TError,
          Awaited<ReturnType<typeof appSyncStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppSyncStatus<TData = Awaited<ReturnType<typeof appSyncStatus>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appSyncStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appSyncStatus>>,
          TError,
          Awaited<ReturnType<typeof appSyncStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppSyncStatus<TData = Awaited<ReturnType<typeof appSyncStatus>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appSyncStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current sync status for this app
 */

export function useAppSyncStatus<TData = Awaited<ReturnType<typeof appSyncStatus>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appSyncStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppSyncStatusQueryOptions(platform,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Track an app
 */
export type trackAppResponse204 = {
  data: void
  status: 204
}

export type trackAppResponseSuccess = (trackAppResponse204) & {
  headers: Headers;
};
;

export type trackAppResponse = (trackAppResponseSuccess)

export const getTrackAppUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/apps/${platform}/${externalId}/track`
}

export const trackApp = async (platform: 'ios' | 'android',
    externalId: string, options?: RequestInit): Promise<trackAppResponse> => {

  const res = await fetch(getTrackAppUrl(platform,externalId),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: trackAppResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as trackAppResponse
}




export const getTrackAppMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof trackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext> => {

const mutationKey = ['trackApp'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof trackApp>>, {platform: 'ios' | 'android';externalId: string}> = (props) => {
          const {platform,externalId} = props ?? {};

          return  trackApp(platform,externalId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TrackAppMutationResult = NonNullable<Awaited<ReturnType<typeof trackApp>>>

    export type TrackAppMutationError = unknown

    /**
 * @summary Track an app
 */
export const useTrackApp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof trackApp>>,
        TError,
        {platform: 'ios' | 'android';externalId: string},
        TContext
      > => {
      return useMutation(getTrackAppMutationOptions(options), queryClient);
    }
    /**
 * @summary Untrack an app
 */
export type untrackAppResponse204 = {
  data: void
  status: 204
}

export type untrackAppResponseSuccess = (untrackAppResponse204) & {
  headers: Headers;
};
;

export type untrackAppResponse = (untrackAppResponseSuccess)

export const getUntrackAppUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/apps/${platform}/${externalId}/track`
}

export const untrackApp = async (platform: 'ios' | 'android',
    externalId: string, options?: RequestInit): Promise<untrackAppResponse> => {

  const res = await fetch(getUntrackAppUrl(platform,externalId),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: untrackAppResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as untrackAppResponse
}




export const getUntrackAppMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof untrackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof untrackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext> => {

const mutationKey = ['untrackApp'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof untrackApp>>, {platform: 'ios' | 'android';externalId: string}> = (props) => {
          const {platform,externalId} = props ?? {};

          return  untrackApp(platform,externalId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UntrackAppMutationResult = NonNullable<Awaited<ReturnType<typeof untrackApp>>>

    export type UntrackAppMutationError = unknown

    /**
 * @summary Untrack an app
 */
export const useUntrackApp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof untrackApp>>, TError,{platform: 'ios' | 'android';externalId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof untrackApp>>,
        TError,
        {platform: 'ios' | 'android';externalId: string},
        TContext
      > => {
      return useMutation(getUntrackAppMutationOptions(options), queryClient);
    }
    /**
 * @summary List chart rankings for an app on a given date
 */
export type listAppRankingsResponse200 = {
  data: AppRankingResource[]
  status: 200
}

export type listAppRankingsResponse404 = {
  data: void
  status: 404
}

export type listAppRankingsResponseSuccess = (listAppRankingsResponse200) & {
  headers: Headers;
};
export type listAppRankingsResponseError = (listAppRankingsResponse404) & {
  headers: Headers;
};

export type listAppRankingsResponse = (listAppRankingsResponseSuccess | listAppRankingsResponseError)

export const getListAppRankingsUrl = (platform: 'ios' | 'android',
    externalId: string,
    params?: ListAppRankingsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/apps/${platform}/${externalId}/rankings?${stringifiedParams}` : `/api/v1/apps/${platform}/${externalId}/rankings`
}

export const listAppRankings = async (platform: 'ios' | 'android',
    externalId: string,
    params?: ListAppRankingsParams, options?: RequestInit): Promise<listAppRankingsResponse> => {

  const res = await fetch(getListAppRankingsUrl(platform,externalId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listAppRankingsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listAppRankingsResponse
}





export const getListAppRankingsQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: ListAppRankingsParams,) => {
    return [
    `/api/v1/apps/${platform}/${externalId}/rankings`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAppRankingsQueryOptions = <TData = Awaited<ReturnType<typeof listAppRankings>>, TError = void>(platform: 'ios' | 'android',
    externalId: string,
    params?: ListAppRankingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppRankings>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAppRankingsQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAppRankings>>> = ({ signal }) => listAppRankings(platform,externalId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAppRankings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAppRankingsQueryResult = NonNullable<Awaited<ReturnType<typeof listAppRankings>>>
export type ListAppRankingsQueryError = void


export function useListAppRankings<TData = Awaited<ReturnType<typeof listAppRankings>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: undefined |  ListAppRankingsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppRankings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAppRankings>>,
          TError,
          Awaited<ReturnType<typeof listAppRankings>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAppRankings<TData = Awaited<ReturnType<typeof listAppRankings>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: ListAppRankingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppRankings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAppRankings>>,
          TError,
          Awaited<ReturnType<typeof listAppRankings>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAppRankings<TData = Awaited<ReturnType<typeof listAppRankings>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: ListAppRankingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppRankings>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List chart rankings for an app on a given date
 */

export function useListAppRankings<TData = Awaited<ReturnType<typeof listAppRankings>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: ListAppRankingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppRankings>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAppRankingsQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Search apps in stores
 */
export type searchAppsResponse200 = {
  data: AppResource[]
  status: 200
}

export type searchAppsResponseSuccess = (searchAppsResponse200) & {
  headers: Headers;
};
;

export type searchAppsResponse = (searchAppsResponseSuccess)

export const getSearchAppsUrl = (params: SearchAppsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/apps/search?${stringifiedParams}` : `/api/v1/apps/search`
}

export const searchApps = async (params: SearchAppsParams, options?: RequestInit): Promise<searchAppsResponse> => {

  const res = await fetch(getSearchAppsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchAppsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchAppsResponse
}





export const getSearchAppsQueryKey = (params?: SearchAppsParams,) => {
    return [
    `/api/v1/apps/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchAppsQueryOptions = <TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(params: SearchAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchAppsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchApps>>> = ({ signal }) => searchApps(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchAppsQueryResult = NonNullable<Awaited<ReturnType<typeof searchApps>>>
export type SearchAppsQueryError = unknown


export function useSearchApps<TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(
 params: SearchAppsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchApps>>,
          TError,
          Awaited<ReturnType<typeof searchApps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchApps<TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(
 params: SearchAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchApps>>,
          TError,
          Awaited<ReturnType<typeof searchApps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchApps<TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(
 params: SearchAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search apps in stores
 */

export function useSearchApps<TData = Awaited<ReturnType<typeof searchApps>>, TError = unknown>(
 params: SearchAppsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchAppsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List competitors for an app
 */
export type listCompetitorsResponse200 = {
  data: CompetitorResource[]
  status: 200
}

export type listCompetitorsResponse404 = {
  data: void
  status: 404
}

export type listCompetitorsResponseSuccess = (listCompetitorsResponse200) & {
  headers: Headers;
};
export type listCompetitorsResponseError = (listCompetitorsResponse404) & {
  headers: Headers;
};

export type listCompetitorsResponse = (listCompetitorsResponseSuccess | listCompetitorsResponseError)

export const getListCompetitorsUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/apps/${platform}/${externalId}/competitors`
}

export const listCompetitors = async (platform: 'ios' | 'android',
    externalId: string, options?: RequestInit): Promise<listCompetitorsResponse> => {

  const res = await fetch(getListCompetitorsUrl(platform,externalId),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listCompetitorsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listCompetitorsResponse
}





export const getListCompetitorsQueryKey = (platform: 'ios' | 'android',
    externalId: string,) => {
    return [
    `/api/v1/apps/${platform}/${externalId}/competitors`
    ] as const;
    }


export const getListCompetitorsQueryOptions = <TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCompetitorsQueryKey(platform,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCompetitors>>> = ({ signal }) => listCompetitors(platform,externalId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCompetitorsQueryResult = NonNullable<Awaited<ReturnType<typeof listCompetitors>>>
export type ListCompetitorsQueryError = void


export function useListCompetitors<TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCompetitors>>,
          TError,
          Awaited<ReturnType<typeof listCompetitors>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCompetitors<TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCompetitors>>,
          TError,
          Awaited<ReturnType<typeof listCompetitors>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCompetitors<TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List competitors for an app
 */

export function useListCompetitors<TData = Awaited<ReturnType<typeof listCompetitors>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompetitors>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCompetitorsQueryOptions(platform,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Add a competitor to an app
 */
export type storeCompetitorResponse201 = {
  data: CompetitorResource
  status: 201
}

export type storeCompetitorResponse404 = {
  data: void
  status: 404
}

export type storeCompetitorResponse422 = {
  data: void
  status: 422
}

export type storeCompetitorResponseSuccess = (storeCompetitorResponse201) & {
  headers: Headers;
};
export type storeCompetitorResponseError = (storeCompetitorResponse404 | storeCompetitorResponse422) & {
  headers: Headers;
};

export type storeCompetitorResponse = (storeCompetitorResponseSuccess | storeCompetitorResponseError)

export const getStoreCompetitorUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/apps/${platform}/${externalId}/competitors`
}

export const storeCompetitor = async (platform: 'ios' | 'android',
    externalId: string,
    storeCompetitorRequest: StoreCompetitorRequest, options?: RequestInit): Promise<storeCompetitorResponse> => {

  const res = await fetch(getStoreCompetitorUrl(platform,externalId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeCompetitorRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: storeCompetitorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as storeCompetitorResponse
}




export const getStoreCompetitorMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof storeCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest}, TContext> => {

const mutationKey = ['storeCompetitor'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storeCompetitor>>, {platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest}> = (props) => {
          const {platform,externalId,data} = props ?? {};

          return  storeCompetitor(platform,externalId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StoreCompetitorMutationResult = NonNullable<Awaited<ReturnType<typeof storeCompetitor>>>
    export type StoreCompetitorMutationBody = StoreCompetitorRequest
    export type StoreCompetitorMutationError = void

    /**
 * @summary Add a competitor to an app
 */
export const useStoreCompetitor = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof storeCompetitor>>,
        TError,
        {platform: 'ios' | 'android';externalId: string;data: StoreCompetitorRequest},
        TContext
      > => {
      return useMutation(getStoreCompetitorMutationOptions(options), queryClient);
    }
    /**
 * @summary List competitors grouped by parent app across all user apps
 */
export type listAllCompetitorsResponse200 = {
  data: CompetitorGroupResource[]
  status: 200
}

export type listAllCompetitorsResponseSuccess = (listAllCompetitorsResponse200) & {
  headers: Headers;
};
;

export type listAllCompetitorsResponse = (listAllCompetitorsResponseSuccess)

export const getListAllCompetitorsUrl = () => {




  return `/api/v1/competitors`
}

export const listAllCompetitors = async ( options?: RequestInit): Promise<listAllCompetitorsResponse> => {

  const res = await fetch(getListAllCompetitorsUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listAllCompetitorsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listAllCompetitorsResponse
}





export const getListAllCompetitorsQueryKey = () => {
    return [
    `/api/v1/competitors`
    ] as const;
    }


export const getListAllCompetitorsQueryOptions = <TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAllCompetitorsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllCompetitors>>> = ({ signal }) => listAllCompetitors({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAllCompetitorsQueryResult = NonNullable<Awaited<ReturnType<typeof listAllCompetitors>>>
export type ListAllCompetitorsQueryError = unknown


export function useListAllCompetitors<TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllCompetitors>>,
          TError,
          Awaited<ReturnType<typeof listAllCompetitors>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAllCompetitors<TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllCompetitors>>,
          TError,
          Awaited<ReturnType<typeof listAllCompetitors>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAllCompetitors<TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List competitors grouped by parent app across all user apps
 */

export function useListAllCompetitors<TData = Awaited<ReturnType<typeof listAllCompetitors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompetitors>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAllCompetitorsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Remove a competitor from an app
 */
export type deleteCompetitorResponse204 = {
  data: void
  status: 204
}

export type deleteCompetitorResponse404 = {
  data: void
  status: 404
}

export type deleteCompetitorResponseSuccess = (deleteCompetitorResponse204) & {
  headers: Headers;
};
export type deleteCompetitorResponseError = (deleteCompetitorResponse404) & {
  headers: Headers;
};

export type deleteCompetitorResponse = (deleteCompetitorResponseSuccess | deleteCompetitorResponseError)

export const getDeleteCompetitorUrl = (platform: 'ios' | 'android',
    externalId: string,
    competitor: number,) => {




  return `/api/v1/apps/${platform}/${externalId}/competitors/${competitor}`
}

export const deleteCompetitor = async (platform: 'ios' | 'android',
    externalId: string,
    competitor: number, options?: RequestInit): Promise<deleteCompetitorResponse> => {

  const res = await fetch(getDeleteCompetitorUrl(platform,externalId,competitor),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteCompetitorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteCompetitorResponse
}




export const getDeleteCompetitorMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;competitor: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;competitor: number}, TContext> => {

const mutationKey = ['deleteCompetitor'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCompetitor>>, {platform: 'ios' | 'android';externalId: string;competitor: number}> = (props) => {
          const {platform,externalId,competitor} = props ?? {};

          return  deleteCompetitor(platform,externalId,competitor,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCompetitorMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCompetitor>>>

    export type DeleteCompetitorMutationError = void

    /**
 * @summary Remove a competitor from an app
 */
export const useDeleteCompetitor = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompetitor>>, TError,{platform: 'ios' | 'android';externalId: string;competitor: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCompetitor>>,
        TError,
        {platform: 'ios' | 'android';externalId: string;competitor: number},
        TContext
      > => {
      return useMutation(getDeleteCompetitorMutationOptions(options), queryClient);
    }
    /**
 * @summary Get keyword density for an app
 */
export type appKeywordsResponse200 = {
  data: KeywordDensityResource[]
  status: 200
}

export type appKeywordsResponse404 = {
  data: void
  status: 404
}

export type appKeywordsResponseSuccess = (appKeywordsResponse200) & {
  headers: Headers;
};
export type appKeywordsResponseError = (appKeywordsResponse404) & {
  headers: Headers;
};

export type appKeywordsResponse = (appKeywordsResponseSuccess | appKeywordsResponseError)

export const getAppKeywordsUrl = (platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/apps/${platform}/${externalId}/keywords?${stringifiedParams}` : `/api/v1/apps/${platform}/${externalId}/keywords`
}

export const appKeywords = async (platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams, options?: RequestInit): Promise<appKeywordsResponse> => {

  const res = await fetch(getAppKeywordsUrl(platform,externalId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appKeywordsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appKeywordsResponse
}





export const getAppKeywordsQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams,) => {
    return [
    `/api/v1/apps/${platform}/${externalId}/keywords`, ...(params ? [params] : [])
    ] as const;
    }


export const getAppKeywordsQueryOptions = <TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppKeywordsQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appKeywords>>> = ({ signal }) => appKeywords(platform,externalId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppKeywordsQueryResult = NonNullable<Awaited<ReturnType<typeof appKeywords>>>
export type AppKeywordsQueryError = void


export function useAppKeywords<TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: undefined |  AppKeywordsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appKeywords>>,
          TError,
          Awaited<ReturnType<typeof appKeywords>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppKeywords<TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appKeywords>>,
          TError,
          Awaited<ReturnType<typeof appKeywords>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppKeywords<TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get keyword density for an app
 */

export function useAppKeywords<TData = Awaited<ReturnType<typeof appKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: AppKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appKeywords>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppKeywordsQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Compare keyword density with other apps
 */
export type compareKeywordsResponse200 = {
  data: KeywordCompareResource
  status: 200
}

export type compareKeywordsResponse404 = {
  data: void
  status: 404
}

export type compareKeywordsResponseSuccess = (compareKeywordsResponse200) & {
  headers: Headers;
};
export type compareKeywordsResponseError = (compareKeywordsResponse404) & {
  headers: Headers;
};

export type compareKeywordsResponse = (compareKeywordsResponseSuccess | compareKeywordsResponseError)

export const getCompareKeywordsUrl = (platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/apps/${platform}/${externalId}/keywords/compare?${stringifiedParams}` : `/api/v1/apps/${platform}/${externalId}/keywords/compare`
}

export const compareKeywords = async (platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options?: RequestInit): Promise<compareKeywordsResponse> => {

  const res = await fetch(getCompareKeywordsUrl(platform,externalId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: compareKeywordsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as compareKeywordsResponse
}





export const getCompareKeywordsQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: CompareKeywordsParams,) => {
    return [
    `/api/v1/apps/${platform}/${externalId}/keywords/compare`, ...(params ? [params] : [])
    ] as const;
    }


export const getCompareKeywordsQueryOptions = <TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCompareKeywordsQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof compareKeywords>>> = ({ signal }) => compareKeywords(platform,externalId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CompareKeywordsQueryResult = NonNullable<Awaited<ReturnType<typeof compareKeywords>>>
export type CompareKeywordsQueryError = void


export function useCompareKeywords<TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof compareKeywords>>,
          TError,
          Awaited<ReturnType<typeof compareKeywords>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompareKeywords<TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof compareKeywords>>,
          TError,
          Awaited<ReturnType<typeof compareKeywords>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompareKeywords<TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Compare keyword density with other apps
 */

export function useCompareKeywords<TData = Awaited<ReturnType<typeof compareKeywords>>, TError = void>(
 platform: 'ios' | 'android',
    externalId: string,
    params: CompareKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compareKeywords>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCompareKeywordsQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




