/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ImportPublisherAppsBody,
  PublisherDetailResource,
  PublisherResource,
  PublisherSearchResultResource,
  PublisherStoreApps200,
  SearchPublishersParams,
  ShowPublisherParams
} from '../../models';





/**
 * @summary Search publishers across stores
 */
export type searchPublishersResponse200 = {
  data: PublisherSearchResultResource[]
  status: 200
}

export type searchPublishersResponseSuccess = (searchPublishersResponse200) & {
  headers: Headers;
};
;

export type searchPublishersResponse = (searchPublishersResponseSuccess)

export const getSearchPublishersUrl = (params: SearchPublishersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/publishers/search?${stringifiedParams}` : `/api/v1/publishers/search`
}

export const searchPublishers = async (params: SearchPublishersParams, options?: RequestInit): Promise<searchPublishersResponse> => {

  const res = await fetch(getSearchPublishersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchPublishersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchPublishersResponse
}





export const getSearchPublishersQueryKey = (params?: SearchPublishersParams,) => {
    return [
    `/api/v1/publishers/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchPublishersQueryOptions = <TData = Awaited<ReturnType<typeof searchPublishers>>, TError = unknown>(params: SearchPublishersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPublishers>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchPublishersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchPublishers>>> = ({ signal }) => searchPublishers(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchPublishers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchPublishersQueryResult = NonNullable<Awaited<ReturnType<typeof searchPublishers>>>
export type SearchPublishersQueryError = unknown


export function useSearchPublishers<TData = Awaited<ReturnType<typeof searchPublishers>>, TError = unknown>(
 params: SearchPublishersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPublishers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchPublishers>>,
          TError,
          Awaited<ReturnType<typeof searchPublishers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchPublishers<TData = Awaited<ReturnType<typeof searchPublishers>>, TError = unknown>(
 params: SearchPublishersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPublishers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchPublishers>>,
          TError,
          Awaited<ReturnType<typeof searchPublishers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchPublishers<TData = Awaited<ReturnType<typeof searchPublishers>>, TError = unknown>(
 params: SearchPublishersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPublishers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search publishers across stores
 */

export function useSearchPublishers<TData = Awaited<ReturnType<typeof searchPublishers>>, TError = unknown>(
 params: SearchPublishersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPublishers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchPublishersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List publishers from user apps
 */
export type listPublishersResponse200 = {
  data: PublisherResource[]
  status: 200
}

export type listPublishersResponseSuccess = (listPublishersResponse200) & {
  headers: Headers;
};
;

export type listPublishersResponse = (listPublishersResponseSuccess)

export const getListPublishersUrl = () => {




  return `/api/v1/publishers`
}

export const listPublishers = async ( options?: RequestInit): Promise<listPublishersResponse> => {

  const res = await fetch(getListPublishersUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listPublishersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listPublishersResponse
}





export const getListPublishersQueryKey = () => {
    return [
    `/api/v1/publishers`
    ] as const;
    }


export const getListPublishersQueryOptions = <TData = Awaited<ReturnType<typeof listPublishers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublishers>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPublishersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPublishers>>> = ({ signal }) => listPublishers({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPublishers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPublishersQueryResult = NonNullable<Awaited<ReturnType<typeof listPublishers>>>
export type ListPublishersQueryError = unknown


export function useListPublishers<TData = Awaited<ReturnType<typeof listPublishers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublishers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPublishers>>,
          TError,
          Awaited<ReturnType<typeof listPublishers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPublishers<TData = Awaited<ReturnType<typeof listPublishers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublishers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPublishers>>,
          TError,
          Awaited<ReturnType<typeof listPublishers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPublishers<TData = Awaited<ReturnType<typeof listPublishers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublishers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List publishers from user apps
 */

export function useListPublishers<TData = Awaited<ReturnType<typeof listPublishers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublishers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPublishersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get publisher details with tracked apps
 */
export type showPublisherResponse200 = {
  data: PublisherDetailResource
  status: 200
}

export type showPublisherResponseSuccess = (showPublisherResponse200) & {
  headers: Headers;
};
;

export type showPublisherResponse = (showPublisherResponseSuccess)

export const getShowPublisherUrl = (platform: 'ios' | 'android',
    externalId: string,
    params?: ShowPublisherParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/publishers/${platform}/${externalId}?${stringifiedParams}` : `/api/v1/publishers/${platform}/${externalId}`
}

export const showPublisher = async (platform: 'ios' | 'android',
    externalId: string,
    params?: ShowPublisherParams, options?: RequestInit): Promise<showPublisherResponse> => {

  const res = await fetch(getShowPublisherUrl(platform,externalId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: showPublisherResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as showPublisherResponse
}





export const getShowPublisherQueryKey = (platform: 'ios' | 'android',
    externalId: string,
    params?: ShowPublisherParams,) => {
    return [
    `/api/v1/publishers/${platform}/${externalId}`, ...(params ? [params] : [])
    ] as const;
    }


export const getShowPublisherQueryOptions = <TData = Awaited<ReturnType<typeof showPublisher>>, TError = unknown>(platform: 'ios' | 'android',
    externalId: string,
    params?: ShowPublisherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showPublisher>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowPublisherQueryKey(platform,externalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showPublisher>>> = ({ signal }) => showPublisher(platform,externalId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof showPublisher>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowPublisherQueryResult = NonNullable<Awaited<ReturnType<typeof showPublisher>>>
export type ShowPublisherQueryError = unknown


export function useShowPublisher<TData = Awaited<ReturnType<typeof showPublisher>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params: undefined |  ShowPublisherParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof showPublisher>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof showPublisher>>,
          TError,
          Awaited<ReturnType<typeof showPublisher>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowPublisher<TData = Awaited<ReturnType<typeof showPublisher>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: ShowPublisherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showPublisher>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof showPublisher>>,
          TError,
          Awaited<ReturnType<typeof showPublisher>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowPublisher<TData = Awaited<ReturnType<typeof showPublisher>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: ShowPublisherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showPublisher>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get publisher details with tracked apps
 */

export function useShowPublisher<TData = Awaited<ReturnType<typeof showPublisher>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string,
    params?: ShowPublisherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showPublisher>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getShowPublisherQueryOptions(platform,externalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Fetch all apps by publisher from store
 */
export type publisherStoreAppsResponse200 = {
  data: PublisherStoreApps200
  status: 200
}

export type publisherStoreAppsResponseSuccess = (publisherStoreAppsResponse200) & {
  headers: Headers;
};
;

export type publisherStoreAppsResponse = (publisherStoreAppsResponseSuccess)

export const getPublisherStoreAppsUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/publishers/${platform}/${externalId}/store-apps`
}

export const publisherStoreApps = async (platform: 'ios' | 'android',
    externalId: string, options?: RequestInit): Promise<publisherStoreAppsResponse> => {

  const res = await fetch(getPublisherStoreAppsUrl(platform,externalId),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: publisherStoreAppsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as publisherStoreAppsResponse
}





export const getPublisherStoreAppsQueryKey = (platform: 'ios' | 'android',
    externalId: string,) => {
    return [
    `/api/v1/publishers/${platform}/${externalId}/store-apps`
    ] as const;
    }


export const getPublisherStoreAppsQueryOptions = <TData = Awaited<ReturnType<typeof publisherStoreApps>>, TError = unknown>(platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publisherStoreApps>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPublisherStoreAppsQueryKey(platform,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof publisherStoreApps>>> = ({ signal }) => publisherStoreApps(platform,externalId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(platform && externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof publisherStoreApps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PublisherStoreAppsQueryResult = NonNullable<Awaited<ReturnType<typeof publisherStoreApps>>>
export type PublisherStoreAppsQueryError = unknown


export function usePublisherStoreApps<TData = Awaited<ReturnType<typeof publisherStoreApps>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof publisherStoreApps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publisherStoreApps>>,
          TError,
          Awaited<ReturnType<typeof publisherStoreApps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublisherStoreApps<TData = Awaited<ReturnType<typeof publisherStoreApps>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publisherStoreApps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publisherStoreApps>>,
          TError,
          Awaited<ReturnType<typeof publisherStoreApps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublisherStoreApps<TData = Awaited<ReturnType<typeof publisherStoreApps>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publisherStoreApps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch all apps by publisher from store
 */

export function usePublisherStoreApps<TData = Awaited<ReturnType<typeof publisherStoreApps>>, TError = unknown>(
 platform: 'ios' | 'android',
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publisherStoreApps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPublisherStoreAppsQueryOptions(platform,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Import and track apps from publisher
 */
export type importPublisherAppsResponse204 = {
  data: void
  status: 204
}

export type importPublisherAppsResponseSuccess = (importPublisherAppsResponse204) & {
  headers: Headers;
};
;

export type importPublisherAppsResponse = (importPublisherAppsResponseSuccess)

export const getImportPublisherAppsUrl = (platform: 'ios' | 'android',
    externalId: string,) => {




  return `/api/v1/publishers/${platform}/${externalId}/import`
}

export const importPublisherApps = async (platform: 'ios' | 'android',
    externalId: string,
    importPublisherAppsBody: ImportPublisherAppsBody, options?: RequestInit): Promise<importPublisherAppsResponse> => {

  const res = await fetch(getImportPublisherAppsUrl(platform,externalId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      importPublisherAppsBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: importPublisherAppsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as importPublisherAppsResponse
}




export const getImportPublisherAppsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importPublisherApps>>, TError,{platform: 'ios' | 'android';externalId: string;data: ImportPublisherAppsBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof importPublisherApps>>, TError,{platform: 'ios' | 'android';externalId: string;data: ImportPublisherAppsBody}, TContext> => {

const mutationKey = ['importPublisherApps'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importPublisherApps>>, {platform: 'ios' | 'android';externalId: string;data: ImportPublisherAppsBody}> = (props) => {
          const {platform,externalId,data} = props ?? {};

          return  importPublisherApps(platform,externalId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ImportPublisherAppsMutationResult = NonNullable<Awaited<ReturnType<typeof importPublisherApps>>>
    export type ImportPublisherAppsMutationBody = ImportPublisherAppsBody
    export type ImportPublisherAppsMutationError = unknown

    /**
 * @summary Import and track apps from publisher
 */
export const useImportPublisherApps = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importPublisherApps>>, TError,{platform: 'ios' | 'android';externalId: string;data: ImportPublisherAppsBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importPublisherApps>>,
        TError,
        {platform: 'ios' | 'android';externalId: string;data: ImportPublisherAppsBody},
        TContext
      > => {
      return useMutation(getImportPublisherAppsMutationOptions(options), queryClient);
    }
