<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * iOS: Apple App Store Connect locale codes
     * Android: Google Play locale codes
     * null = platform not available in this country
     */
    private const COUNTRIES = [
        ['code' => 'af', 'name' => 'Afghanistan', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'al', 'name' => 'Albania', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'dz', 'name' => 'Algeria', 'ios' => ['ar', 'en-GB'], 'android' => ['ar', 'en-US']],
        ['code' => 'ao', 'name' => 'Angola', 'ios' => null, 'android' => ['en-US', 'pt']],
        ['code' => 'ar', 'name' => 'Argentina', 'ios' => ['es-MX', 'en-GB'], 'android' => ['es-419', 'en-US']],
        ['code' => 'am', 'name' => 'Armenia', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'au', 'name' => 'Australia', 'ios' => ['en-AU'], 'android' => ['en-AU']],
        ['code' => 'at', 'name' => 'Austria', 'ios' => ['de-DE', 'en-GB'], 'android' => ['de-DE', 'en-US']],
        ['code' => 'az', 'name' => 'Azerbaijan', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'bh', 'name' => 'Bahrain', 'ios' => ['ar', 'en-GB'], 'android' => ['ar', 'en-US']],
        ['code' => 'bd', 'name' => 'Bangladesh', 'ios' => null, 'android' => ['en-US', 'bn-BD']],
        ['code' => 'by', 'name' => 'Belarus', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'be', 'name' => 'Belgium', 'ios' => ['en-GB', 'fr-FR', 'nl-NL'], 'android' => ['en-US', 'fr-FR', 'nl-NL']],
        ['code' => 'bo', 'name' => 'Bolivia', 'ios' => null, 'android' => ['es-419', 'en-US']],
        ['code' => 'ba', 'name' => 'Bosnia And Herzegovina', 'ios' => ['hr', 'en-GB'], 'android' => ['hr', 'en-US']],
        ['code' => 'bw', 'name' => 'Botswana', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'br', 'name' => 'Brazil', 'ios' => ['pt-BR', 'en-GB'], 'android' => ['pt-BR', 'en-US']],
        ['code' => 'bg', 'name' => 'Bulgaria', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'kh', 'name' => 'Cambodia', 'ios' => ['en-GB'], 'android' => ['en-US', 'km']],
        ['code' => 'cm', 'name' => 'Cameroon', 'ios' => ['fr-FR', 'en-GB'], 'android' => ['fr-FR', 'en-US']],
        ['code' => 'ca', 'name' => 'Canada', 'ios' => ['en-CA', 'fr-CA'], 'android' => ['en-CA', 'fr-CA']],
        ['code' => 'cl', 'name' => 'Chile', 'ios' => ['es-MX', 'en-GB'], 'android' => ['es-419', 'en-US']],
        ['code' => 'cn', 'name' => 'China', 'ios' => ['zh-Hans', 'en-GB'], 'android' => ['zh-CN', 'en-US']],
        ['code' => 'co', 'name' => 'Colombia', 'ios' => ['es-MX', 'en-GB'], 'android' => ['es-419', 'en-US']],
        ['code' => 'cd', 'name' => 'Congo, The Democratic Republic Of The', 'ios' => ['fr-FR', 'en-GB'], 'android' => ['fr-FR', 'en-US']],
        ['code' => 'cr', 'name' => 'Costa Rica', 'ios' => null, 'android' => ['es-419', 'en-US']],
        ['code' => 'ci', 'name' => "Cote D'ivoire", 'ios' => ['fr-FR', 'en-GB'], 'android' => ['fr-FR', 'en-US']],
        ['code' => 'hr', 'name' => 'Croatia', 'ios' => ['hr', 'en-GB'], 'android' => ['hr', 'en-US']],
        ['code' => 'cy', 'name' => 'Cyprus', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'cz', 'name' => 'Czech Republic', 'ios' => ['cs', 'en-GB'], 'android' => ['cs-CZ', 'en-US']],
        ['code' => 'dk', 'name' => 'Denmark', 'ios' => ['da', 'en-GB'], 'android' => ['da-DK', 'en-US']],
        ['code' => 'do', 'name' => 'Dominican Republic', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'ec', 'name' => 'Ecuador', 'ios' => ['es-MX', 'en-GB'], 'android' => ['es-419', 'en-US']],
        ['code' => 'eg', 'name' => 'Egypt', 'ios' => ['ar', 'en-GB'], 'android' => ['ar', 'en-US']],
        ['code' => 'sv', 'name' => 'El Salvador', 'ios' => null, 'android' => ['es-419', 'en-US']],
        ['code' => 'ee', 'name' => 'Estonia', 'ios' => ['en-GB'], 'android' => ['en-US', 'et']],
        ['code' => 'fi', 'name' => 'Finland', 'ios' => ['fi', 'en-GB'], 'android' => ['fi-FI', 'en-US']],
        ['code' => 'fr', 'name' => 'France', 'ios' => ['fr-FR', 'en-GB'], 'android' => ['fr-FR', 'en-US']],
        ['code' => 'ga', 'name' => 'Gabon', 'ios' => ['fr-FR', 'en-GB'], 'android' => ['fr-FR', 'en-US']],
        ['code' => 'ge', 'name' => 'Georgia', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'de', 'name' => 'Germany', 'ios' => ['de-DE', 'en-GB'], 'android' => ['de-DE', 'en-US']],
        ['code' => 'gh', 'name' => 'Ghana', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'gr', 'name' => 'Greece', 'ios' => ['el', 'en-GB'], 'android' => ['el', 'en-US']],
        ['code' => 'gt', 'name' => 'Guatemala', 'ios' => null, 'android' => ['es-419', 'en-US']],
        ['code' => 'hn', 'name' => 'Honduras', 'ios' => null, 'android' => ['es-419', 'en-US']],
        ['code' => 'hk', 'name' => 'Hong Kong', 'ios' => ['zh-Hant', 'en-GB'], 'android' => ['zh-HK', 'zh-TW', 'en-US']],
        ['code' => 'hu', 'name' => 'Hungary', 'ios' => ['hu', 'en-GB'], 'android' => ['hu', 'en-US']],
        ['code' => 'is', 'name' => 'Iceland', 'ios' => ['en-GB'], 'android' => ['en-US', 'is']],
        ['code' => 'in', 'name' => 'India', 'ios' => ['en-GB', 'hi'], 'android' => ['en-IN', 'en-US', 'hi', 'ta', 'mr', 'te', 'kn', 'ml', 'bn-BD', 'pa']],
        ['code' => 'id', 'name' => 'Indonesia', 'ios' => ['id', 'en-GB'], 'android' => ['id', 'en-US']],
        ['code' => 'ir', 'name' => 'Iran, Islamic Republic Of', 'ios' => null, 'android' => ['en-US', 'fa']],
        ['code' => 'iq', 'name' => 'Iraq', 'ios' => ['en-GB'], 'android' => ['en-US', 'ar']],
        ['code' => 'ie', 'name' => 'Ireland', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'il', 'name' => 'Israel', 'ios' => ['he', 'en-GB'], 'android' => ['he', 'en-US']],
        ['code' => 'it', 'name' => 'Italy', 'ios' => ['it', 'en-GB'], 'android' => ['it', 'en-US']],
        ['code' => 'jp', 'name' => 'Japan', 'ios' => ['ja', 'en-US'], 'android' => ['ja', 'en-US']],
        ['code' => 'jo', 'name' => 'Jordan', 'ios' => ['ar', 'en-GB'], 'android' => ['ar', 'en-US']],
        ['code' => 'kz', 'name' => 'Kazakstan', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'ke', 'name' => 'Kenya', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'kr', 'name' => 'Korea, Republic Of', 'ios' => ['ko', 'en-GB'], 'android' => ['ko', 'en-US']],
        ['code' => 'kw', 'name' => 'Kuwait', 'ios' => ['ar', 'en-GB'], 'android' => ['ar', 'en-US']],
        ['code' => 'la', 'name' => "Lao People's Democratic Republic", 'ios' => null, 'android' => ['en-US', 'lo']],
        ['code' => 'lv', 'name' => 'Latvia', 'ios' => ['en-GB'], 'android' => ['en-US', 'lv']],
        ['code' => 'lb', 'name' => 'Lebanon', 'ios' => ['ar', 'en-GB'], 'android' => ['ar', 'en-US']],
        ['code' => 'ly', 'name' => 'Libyan Arab Jamahiriya', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'lt', 'name' => 'Lithuania', 'ios' => ['en-GB'], 'android' => ['en-US', 'lt']],
        ['code' => 'lu', 'name' => 'Luxembourg', 'ios' => ['en-GB', 'fr-FR', 'de-DE'], 'android' => ['en-US', 'fr-FR', 'de-DE']],
        ['code' => 'mo', 'name' => 'Macau', 'ios' => ['zh-Hant', 'en-GB'], 'android' => ['zh-TW', 'en-US']],
        ['code' => 'mw', 'name' => 'Malawi', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'my', 'name' => 'Malaysia', 'ios' => ['ms', 'en-GB'], 'android' => ['ms', 'en-US', 'zh-CN']],
        ['code' => 'mv', 'name' => 'Maldives', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'mx', 'name' => 'Mexico', 'ios' => ['es-MX', 'en-GB'], 'android' => ['es-419', 'en-US']],
        ['code' => 'me', 'name' => 'Montenegro', 'ios' => ['hr', 'en-GB'], 'android' => ['hr', 'en-US']],
        ['code' => 'ma', 'name' => 'Morocco', 'ios' => ['fr-FR', 'en-GB'], 'android' => ['fr-FR', 'en-US']],
        ['code' => 'mm', 'name' => 'Myanmar', 'ios' => ['en-GB'], 'android' => ['en-US', 'my-MM']],
        ['code' => 'nr', 'name' => 'Nauru', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'np', 'name' => 'Nepal', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'nl', 'name' => 'Netherlands', 'ios' => ['nl-NL', 'en-GB'], 'android' => ['nl-NL', 'en-US']],
        ['code' => 'nz', 'name' => 'New Zealand', 'ios' => ['en-AU'], 'android' => ['en-AU']],
        ['code' => 'ni', 'name' => 'Nicaragua', 'ios' => null, 'android' => ['es-419', 'en-US']],
        ['code' => 'ng', 'name' => 'Nigeria', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'no', 'name' => 'Norway', 'ios' => ['nb', 'en-GB'], 'android' => ['nb-NO', 'en-US']],
        ['code' => 'om', 'name' => 'Oman', 'ios' => ['ar', 'en-GB'], 'android' => ['ar', 'en-US']],
        ['code' => 'pk', 'name' => 'Pakistan', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'pa', 'name' => 'Panama', 'ios' => null, 'android' => ['es-419', 'en-US']],
        ['code' => 'py', 'name' => 'Paraguay', 'ios' => null, 'android' => ['es-419', 'en-US']],
        ['code' => 'pe', 'name' => 'Peru', 'ios' => ['es-MX', 'en-GB'], 'android' => ['es-419', 'en-US']],
        ['code' => 'ph', 'name' => 'Philippines', 'ios' => ['en-GB'], 'android' => ['en-US', 'fil']],
        ['code' => 'pl', 'name' => 'Poland', 'ios' => ['pl', 'en-GB'], 'android' => ['pl', 'en-US']],
        ['code' => 'pt', 'name' => 'Portugal', 'ios' => ['pt-PT', 'en-GB'], 'android' => ['pt-PT', 'en-US']],
        ['code' => 'qa', 'name' => 'Qatar', 'ios' => ['ar', 'en-GB'], 'android' => ['ar', 'en-US']],
        ['code' => 'ro', 'name' => 'Romania', 'ios' => ['ro', 'en-GB'], 'android' => ['ro', 'en-US']],
        ['code' => 'ru', 'name' => 'Russian Federation', 'ios' => ['ru', 'en-GB'], 'android' => ['ru', 'en-US']],
        ['code' => 'rw', 'name' => 'Rwanda', 'ios' => ['fr-FR', 'en-GB'], 'android' => ['fr-FR', 'en-US']],
        ['code' => 'sa', 'name' => 'Saudi Arabia', 'ios' => ['ar', 'en-GB'], 'android' => ['ar', 'en-US']],
        ['code' => 'sn', 'name' => 'Senegal', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'rs', 'name' => 'Serbia', 'ios' => ['hr', 'en-GB'], 'android' => ['hr', 'en-US']],
        ['code' => 'sg', 'name' => 'Singapore', 'ios' => ['en-GB', 'zh-Hans'], 'android' => ['en-SG', 'zh-CN']],
        ['code' => 'sk', 'name' => 'Slovakia', 'ios' => ['sk', 'en-GB'], 'android' => ['sk', 'en-US']],
        ['code' => 'si', 'name' => 'Slovenia', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'za', 'name' => 'South Africa', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'es', 'name' => 'Spain', 'ios' => ['es-ES', 'ca', 'en-GB'], 'android' => ['es-ES', 'ca', 'en-US']],
        ['code' => 'lk', 'name' => 'Sri Lanka', 'ios' => null, 'android' => ['en-US', 'si']],
        ['code' => 'se', 'name' => 'Sweden', 'ios' => ['sv', 'en-GB'], 'android' => ['sv', 'en-US']],
        ['code' => 'ch', 'name' => 'Switzerland', 'ios' => ['de-DE', 'fr-FR', 'it', 'en-GB'], 'android' => ['de-DE', 'fr-FR', 'it', 'en-US']],
        ['code' => 'tw', 'name' => 'Taiwan, Province Of China', 'ios' => ['zh-Hant', 'en-GB'], 'android' => ['zh-TW', 'en-US']],
        ['code' => 'tz', 'name' => 'Tanzania', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'th', 'name' => 'Thailand', 'ios' => ['th', 'en-GB'], 'android' => ['th', 'en-US']],
        ['code' => 'xk', 'name' => 'The Republic of Kosovo', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'to', 'name' => 'Tonga', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'tn', 'name' => 'Tunisia', 'ios' => ['ar', 'en-GB'], 'android' => ['ar', 'en-US']],
        ['code' => 'tr', 'name' => 'Turkey', 'ios' => ['tr', 'en-GB'], 'android' => ['tr-TR', 'en-US']],
        ['code' => 'ug', 'name' => 'Uganda', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'ua', 'name' => 'Ukraine', 'ios' => ['uk', 'en-GB'], 'android' => ['uk', 'en-US']],
        ['code' => 'ae', 'name' => 'United Arab Emirates', 'ios' => ['ar', 'en-GB'], 'android' => ['ar', 'en-US']],
        ['code' => 'gb', 'name' => 'United Kingdom', 'ios' => ['en-GB'], 'android' => ['en-GB']],
        ['code' => 'us', 'name' => 'United States', 'ios' => ['en-US', 'es-MX'], 'android' => ['en-US', 'es-419']],
        ['code' => 'uy', 'name' => 'Uruguay', 'ios' => ['es-MX', 'en-GB'], 'android' => ['es-419', 'en-US']],
        ['code' => 'uz', 'name' => 'Uzbekistan', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'vu', 'name' => 'Vanuatu', 'ios' => ['fr-FR', 'en-GB'], 'android' => ['fr-FR', 'en-US']],
        ['code' => 've', 'name' => 'Venezuela', 'ios' => ['es-MX', 'en-GB'], 'android' => ['es-419', 'en-US']],
        ['code' => 'vn', 'name' => 'Viet Nam', 'ios' => ['vi', 'en-GB'], 'android' => ['vi', 'en-US']],
        ['code' => 'zm', 'name' => 'Zambia', 'ios' => ['en-GB'], 'android' => ['en-US']],
        ['code' => 'zw', 'name' => 'Zimbabwe', 'ios' => ['en-GB'], 'android' => ['en-US']],
    ];

    /**
     * iOS cross-localizable languages indexed per country.
     * Apple indexes these additional languages in search for each storefront.
     * Uses Apple App Store Connect locale codes.
     */
    private const IOS_CROSS_LOCALIZABLE = [
        'us' => ['es-MX', 'ru', 'zh-Hans', 'ar', 'fr-FR', 'pt-BR', 'zh-Hant', 'vi', 'ko'],
        'gb' => ['en-AU'],
        'dz' => ['fr-FR', 'en-GB'],
        'ar' => ['en-GB'],
        'au' => ['en-GB'],
        'at' => ['en-GB'],
        'bh' => ['en-GB'],
        'be' => ['fr-FR', 'nl-NL'],
        'bo' => ['en-GB'],
        'br' => ['en-GB'],
        'kh' => ['fr-FR'],
        'ca' => ['fr-CA'],
        'cl' => ['en-GB'],
        'cn' => ['en-GB'],
        'co' => ['en-GB'],
        'cd' => ['fr-FR'],
        'cr' => ['en-GB'],
        'hr' => ['en-GB'],
        'cy' => ['el', 'tr'],
        'cz' => ['en-GB'],
        'dk' => ['da'],
        'do' => ['en-GB'],
        'ec' => ['en-GB'],
        'eg' => ['fr-FR', 'en-GB'],
        'sv' => ['en-GB'],
        'fi' => ['fi'],
        'fr' => ['en-GB'],
        'de' => ['en-GB'],
        'gr' => ['en-GB'],
        'gt' => ['en-GB'],
        'hn' => ['en-GB'],
        'hk' => ['en-GB', 'yue'],
        'hu' => ['en-GB'],
        'in' => ['en-GB'],
        'id' => ['en-GB'],
        'il' => ['en-GB'],
        'it' => ['en-GB'],
        'jp' => ['en-US'],
        'jo' => ['en-GB'],
        'kr' => ['en-GB'],
        'kw' => ['en-GB'],
        'lb' => ['fr-FR', 'en-GB'],
        'lu' => ['fr-FR', 'de-DE'],
        'mo' => ['en-GB', 'zh-Hant'],
        'my' => ['en-GB'],
        'mx' => ['en-GB'],
        'nl' => ['en-GB'],
        'nz' => ['en-GB'],
        'ni' => ['en-GB'],
        'no' => ['en-GB'],
        'pa' => ['en-GB'],
        'py' => ['en-GB'],
        'pe' => ['en-GB'],
        'pl' => ['en-GB'],
        'pt' => ['en-GB'],
        'ro' => ['en-GB'],
        'ru' => ['en-GB', 'uk'],
        'sa' => ['en-GB'],
        'sn' => ['fr-FR'],
        'sg' => ['en-GB'],
        'sk' => ['en-GB'],
        'es' => ['en-GB', 'ca'],
        'se' => ['en-GB'],
        'ch' => ['en-GB', 'fr-FR', 'it'],
        'tw' => ['en-GB'],
        'th' => ['en-GB'],
        'tn' => ['fr-FR', 'en-GB'],
        'tr' => ['en-GB', 'fr-FR'],
        'ua' => ['ru', 'en-GB'],
        'ae' => ['en-GB'],
        'uy' => ['en-GB'],
        've' => ['en-GB'],
        'vn' => ['en-GB'],
    ];

    private const PRIORITIES = [
        'us' => 100,
        'gb' => 80, 'de' => 80, 'fr' => 80, 'jp' => 80,
        'tr' => 60, 'br' => 60, 'in' => 60,
        'kr' => 50, 'au' => 50, 'ca' => 50, 'es' => 50, 'it' => 50,
        'nl' => 40, 'ru' => 40, 'mx' => 40, 'sa' => 40, 'ae' => 40,
    ];

    private const EMOJIS = [
        'af' => "\u{1F1E6}\u{1F1EB}", 'al' => "\u{1F1E6}\u{1F1F1}", 'dz' => "\u{1F1E9}\u{1F1FF}",
        'ao' => "\u{1F1E6}\u{1F1F4}", 'ar' => "\u{1F1E6}\u{1F1F7}", 'am' => "\u{1F1E6}\u{1F1F2}",
        'au' => "\u{1F1E6}\u{1F1FA}", 'at' => "\u{1F1E6}\u{1F1F9}", 'az' => "\u{1F1E6}\u{1F1FF}",
        'bh' => "\u{1F1E7}\u{1F1ED}", 'bd' => "\u{1F1E7}\u{1F1E9}", 'by' => "\u{1F1E7}\u{1F1FE}",
        'be' => "\u{1F1E7}\u{1F1EA}", 'bo' => "\u{1F1E7}\u{1F1F4}", 'ba' => "\u{1F1E7}\u{1F1E6}",
        'bw' => "\u{1F1E7}\u{1F1FC}", 'br' => "\u{1F1E7}\u{1F1F7}", 'bg' => "\u{1F1E7}\u{1F1EC}",
        'kh' => "\u{1F1F0}\u{1F1ED}", 'cm' => "\u{1F1E8}\u{1F1F2}", 'ca' => "\u{1F1E8}\u{1F1E6}",
        'cl' => "\u{1F1E8}\u{1F1F1}", 'cn' => "\u{1F1E8}\u{1F1F3}", 'co' => "\u{1F1E8}\u{1F1F4}",
        'cd' => "\u{1F1E8}\u{1F1E9}", 'cr' => "\u{1F1E8}\u{1F1F7}", 'ci' => "\u{1F1E8}\u{1F1EE}",
        'hr' => "\u{1F1ED}\u{1F1F7}", 'cy' => "\u{1F1E8}\u{1F1FE}", 'cz' => "\u{1F1E8}\u{1F1FF}",
        'dk' => "\u{1F1E9}\u{1F1F0}", 'do' => "\u{1F1E9}\u{1F1F4}", 'ec' => "\u{1F1EA}\u{1F1E8}",
        'eg' => "\u{1F1EA}\u{1F1EC}", 'sv' => "\u{1F1F8}\u{1F1FB}", 'ee' => "\u{1F1EA}\u{1F1EA}",
        'fi' => "\u{1F1EB}\u{1F1EE}", 'fr' => "\u{1F1EB}\u{1F1F7}", 'ga' => "\u{1F1EC}\u{1F1E6}",
        'ge' => "\u{1F1EC}\u{1F1EA}", 'de' => "\u{1F1E9}\u{1F1EA}", 'gh' => "\u{1F1EC}\u{1F1ED}",
        'gr' => "\u{1F1EC}\u{1F1F7}", 'gt' => "\u{1F1EC}\u{1F1F9}", 'hn' => "\u{1F1ED}\u{1F1F3}",
        'hk' => "\u{1F1ED}\u{1F1F0}", 'hu' => "\u{1F1ED}\u{1F1FA}", 'is' => "\u{1F1EE}\u{1F1F8}",
        'in' => "\u{1F1EE}\u{1F1F3}", 'id' => "\u{1F1EE}\u{1F1E9}", 'ir' => "\u{1F1EE}\u{1F1F7}",
        'iq' => "\u{1F1EE}\u{1F1F6}", 'ie' => "\u{1F1EE}\u{1F1EA}", 'il' => "\u{1F1EE}\u{1F1F1}",
        'it' => "\u{1F1EE}\u{1F1F9}", 'jp' => "\u{1F1EF}\u{1F1F5}", 'jo' => "\u{1F1EF}\u{1F1F4}",
        'kz' => "\u{1F1F0}\u{1F1FF}", 'ke' => "\u{1F1F0}\u{1F1EA}", 'kr' => "\u{1F1F0}\u{1F1F7}",
        'kw' => "\u{1F1F0}\u{1F1FC}", 'la' => "\u{1F1F1}\u{1F1E6}", 'lv' => "\u{1F1F1}\u{1F1FB}",
        'lb' => "\u{1F1F1}\u{1F1E7}", 'ly' => "\u{1F1F1}\u{1F1FE}", 'lt' => "\u{1F1F1}\u{1F1F9}",
        'lu' => "\u{1F1F1}\u{1F1FA}", 'mo' => "\u{1F1F2}\u{1F1F4}", 'mw' => "\u{1F1F2}\u{1F1FC}",
        'my' => "\u{1F1F2}\u{1F1FE}", 'mv' => "\u{1F1F2}\u{1F1FB}", 'mx' => "\u{1F1F2}\u{1F1FD}",
        'me' => "\u{1F1F2}\u{1F1EA}", 'ma' => "\u{1F1F2}\u{1F1E6}", 'mm' => "\u{1F1F2}\u{1F1F2}",
        'nr' => "\u{1F1F3}\u{1F1F7}", 'np' => "\u{1F1F3}\u{1F1F5}", 'nl' => "\u{1F1F3}\u{1F1F1}",
        'nz' => "\u{1F1F3}\u{1F1FF}", 'ni' => "\u{1F1F3}\u{1F1EE}", 'ng' => "\u{1F1F3}\u{1F1EC}",
        'no' => "\u{1F1F3}\u{1F1F4}", 'om' => "\u{1F1F4}\u{1F1F2}", 'pk' => "\u{1F1F5}\u{1F1F0}",
        'pa' => "\u{1F1F5}\u{1F1E6}", 'py' => "\u{1F1F5}\u{1F1FE}", 'pe' => "\u{1F1F5}\u{1F1EA}",
        'ph' => "\u{1F1F5}\u{1F1ED}", 'pl' => "\u{1F1F5}\u{1F1F1}", 'pt' => "\u{1F1F5}\u{1F1F9}",
        'qa' => "\u{1F1F6}\u{1F1E6}", 'ro' => "\u{1F1F7}\u{1F1F4}", 'ru' => "\u{1F1F7}\u{1F1FA}",
        'rw' => "\u{1F1F7}\u{1F1FC}", 'sa' => "\u{1F1F8}\u{1F1E6}", 'sn' => "\u{1F1F8}\u{1F1F3}",
        'rs' => "\u{1F1F7}\u{1F1F8}", 'sg' => "\u{1F1F8}\u{1F1EC}", 'sk' => "\u{1F1F8}\u{1F1F0}",
        'si' => "\u{1F1F8}\u{1F1EE}", 'za' => "\u{1F1FF}\u{1F1E6}", 'es' => "\u{1F1EA}\u{1F1F8}",
        'lk' => "\u{1F1F1}\u{1F1F0}", 'se' => "\u{1F1F8}\u{1F1EA}", 'ch' => "\u{1F1E8}\u{1F1ED}",
        'tw' => "\u{1F1F9}\u{1F1FC}", 'tz' => "\u{1F1F9}\u{1F1FF}", 'th' => "\u{1F1F9}\u{1F1ED}",
        'xk' => "\u{1F1FD}\u{1F1F0}", 'to' => "\u{1F1F9}\u{1F1F4}", 'tn' => "\u{1F1F9}\u{1F1F3}",
        'tr' => "\u{1F1F9}\u{1F1F7}", 'ug' => "\u{1F1FA}\u{1F1EC}", 'ua' => "\u{1F1FA}\u{1F1E6}",
        'ae' => "\u{1F1E6}\u{1F1EA}", 'gb' => "\u{1F1EC}\u{1F1E7}", 'us' => "\u{1F1FA}\u{1F1F8}",
        'uy' => "\u{1F1FA}\u{1F1FE}", 'uz' => "\u{1F1FA}\u{1F1FF}", 'vu' => "\u{1F1FB}\u{1F1FA}",
        've' => "\u{1F1FB}\u{1F1EA}", 'vn' => "\u{1F1FB}\u{1F1F3}", 'zm' => "\u{1F1FF}\u{1F1F2}",
        'zw' => "\u{1F1FF}\u{1F1FC}",
    ];

    public function run(): void
    {
        $validCodes = array_column(self::COUNTRIES, 'code');

        Country::whereNotIn('code', $validCodes)->delete();

        $records = [];

        foreach (self::COUNTRIES as $country) {
            $code = $country['code'];
            $cross = self::IOS_CROSS_LOCALIZABLE[$code] ?? null;

            $records[] = [
                'code' => $code,
                'name' => $country['name'],
                'emoji' => self::EMOJIS[$code] ?? '',
                'is_active_ios' => $country['ios'] !== null,
                'is_active_android' => $country['android'] !== null,
                'priority' => self::PRIORITIES[$code] ?? 0,
                'ios_languages' => $country['ios'] ? json_encode($country['ios']) : null,
                'ios_cross_localizable' => $cross ? json_encode($cross) : null,
                'android_languages' => $country['android'] ? json_encode($country['android']) : null,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        Country::upsert($records, ['code'], [
            'name', 'emoji', 'is_active_ios', 'is_active_android', 'priority',
            'ios_languages', 'ios_cross_localizable', 'android_languages', 'updated_at',
        ]);
    }
}
