/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ListStoreCategoriesParams,
  StoreCategory
} from '../../models';





/**
 * @summary List store categories
 */
export type listStoreCategoriesResponse200 = {
  data: StoreCategory[]
  status: 200
}

export type listStoreCategoriesResponseSuccess = (listStoreCategoriesResponse200) & {
  headers: Headers;
};
;

export type listStoreCategoriesResponse = (listStoreCategoriesResponseSuccess)

export const getListStoreCategoriesUrl = (params?: ListStoreCategoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/store-categories?${stringifiedParams}` : `/api/v1/store-categories`
}

export const listStoreCategories = async (params?: ListStoreCategoriesParams, options?: RequestInit): Promise<listStoreCategoriesResponse> => {

  const res = await fetch(getListStoreCategoriesUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listStoreCategoriesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listStoreCategoriesResponse
}





export const getListStoreCategoriesQueryKey = (params?: ListStoreCategoriesParams,) => {
    return [
    `/api/v1/store-categories`, ...(params ? [params] : [])
    ] as const;
    }


export const getListStoreCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof listStoreCategories>>, TError = unknown>(params?: ListStoreCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStoreCategories>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStoreCategoriesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStoreCategories>>> = ({ signal }) => listStoreCategories(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStoreCategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStoreCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof listStoreCategories>>>
export type ListStoreCategoriesQueryError = unknown


export function useListStoreCategories<TData = Awaited<ReturnType<typeof listStoreCategories>>, TError = unknown>(
 params: undefined |  ListStoreCategoriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStoreCategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStoreCategories>>,
          TError,
          Awaited<ReturnType<typeof listStoreCategories>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStoreCategories<TData = Awaited<ReturnType<typeof listStoreCategories>>, TError = unknown>(
 params?: ListStoreCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStoreCategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStoreCategories>>,
          TError,
          Awaited<ReturnType<typeof listStoreCategories>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStoreCategories<TData = Awaited<ReturnType<typeof listStoreCategories>>, TError = unknown>(
 params?: ListStoreCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStoreCategories>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List store categories
 */

export function useListStoreCategories<TData = Awaited<ReturnType<typeof listStoreCategories>>, TError = unknown>(
 params?: ListStoreCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStoreCategories>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStoreCategoriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




