/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetChartsParams
} from '../../models';





/**
 * @summary Get chart rankings
 */
export type getChartsResponse200 = {
  data: void
  status: 200
}

export type getChartsResponseSuccess = (getChartsResponse200) & {
  headers: Headers;
};
;

export type getChartsResponse = (getChartsResponseSuccess)

export const getGetChartsUrl = (params: GetChartsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/charts?${stringifiedParams}` : `/api/v1/charts`
}

export const getCharts = async (params: GetChartsParams, options?: RequestInit): Promise<getChartsResponse> => {

  const res = await fetch(getGetChartsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getChartsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getChartsResponse
}





export const getGetChartsQueryKey = (params?: GetChartsParams,) => {
    return [
    `/api/v1/charts`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetChartsQueryOptions = <TData = Awaited<ReturnType<typeof getCharts>>, TError = unknown>(params: GetChartsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharts>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChartsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCharts>>> = ({ signal }) => getCharts(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCharts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChartsQueryResult = NonNullable<Awaited<ReturnType<typeof getCharts>>>
export type GetChartsQueryError = unknown


export function useGetCharts<TData = Awaited<ReturnType<typeof getCharts>>, TError = unknown>(
 params: GetChartsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCharts>>,
          TError,
          Awaited<ReturnType<typeof getCharts>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCharts<TData = Awaited<ReturnType<typeof getCharts>>, TError = unknown>(
 params: GetChartsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCharts>>,
          TError,
          Awaited<ReturnType<typeof getCharts>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCharts<TData = Awaited<ReturnType<typeof getCharts>>, TError = unknown>(
 params: GetChartsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get chart rankings
 */

export function useGetCharts<TData = Awaited<ReturnType<typeof getCharts>>, TError = unknown>(
 params: GetChartsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChartsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




