/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { AppChangesField } from './appChangesField';
import type { AppChangesPlatform } from './appChangesPlatform';

export type AppChangesParams = {
per_page?: number;
field?: AppChangesField;
platform?: AppChangesPlatform;
/**
 * @maxLength 100
 */
search?: string;
};
