/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { AppMetricRatingBreakdown } from './appMetricRatingBreakdown';

export interface AppMetric {
  id?: number;
  country_code?: string;
  date?: string;
  rating?: number;
  rating_count?: number;
  /** @nullable */
  rating_breakdown?: AppMetricRatingBreakdown;
  /** @nullable */
  rating_delta?: number | null;
  price?: number;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  installs_range?: string | null;
  /** @nullable */
  file_size_bytes?: number | null;
  is_available?: boolean;
}
