/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { AppRankingResourceCategory } from './appRankingResourceCategory';
import type { AppRankingResourceStatus } from './appRankingResourceStatus';

export interface AppRankingResource {
  /** Expects $resource as array with keys:
   country_code, collection, category, rank, previous_rank, status, snapshot_date. */
  country_code?: string;
  collection?: string;
  /** @nullable */
  category?: AppRankingResourceCategory;
  rank?: number;
  /** @nullable */
  previous_rank?: number | null;
  /** @nullable */
  rank_change?: number | null;
  status?: AppRankingResourceStatus;
  snapshot_date?: string;
}
