/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { ChangeAppsRequestField } from './changeAppsRequestField';

export interface ChangeAppsRequest {
  /**
     * @minimum 1
     * @maximum 100
     * @nullable
     */
  per_page?: number | null;
  /** @nullable */
  field?: ChangeAppsRequestField;
}
