/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { ChangeAppsRequestField } from './changeAppsRequestField';
import type { ChangeAppsRequestPlatform } from './changeAppsRequestPlatform';

export interface ChangeAppsRequest {
  /**
     * @minimum 1
     * @maximum 100
     * @nullable
     */
  per_page?: number | null;
  /** @nullable */
  field?: ChangeAppsRequestField;
  /** @nullable */
  platform?: ChangeAppsRequestPlatform;
  /**
     * @maxLength 100
     * @nullable
     */
  search?: string | null;
  /**
     * @minimum 1
     * @nullable
     */
  app_id?: number | null;
  /**
     * @minimum 1
     * @nullable
     */
  page?: number | null;
}
