/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { CompetitorChangesField } from './competitorChangesField';
import type { CompetitorChangesPlatform } from './competitorChangesPlatform';

export type CompetitorChangesParams = {
per_page?: number;
field?: CompetitorChangesField;
platform?: CompetitorChangesPlatform;
/**
 * @maxLength 100
 */
search?: string;
};
