/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

export type Dashboard200RecentReviewsItem = {
  id?: number;
  app_name?: string;
  /** @nullable */
  author?: string | null;
  /** @nullable */
  title?: string | null;
  rating?: number;
  /** @nullable */
  review_date?: string | null;
};
