/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardResourceRecentChangesItem } from './dashboardResourceRecentChangesItem';
import type { DashboardResourceRecentReviewsItem } from './dashboardResourceRecentReviewsItem';

export interface DashboardResource {
  total_apps?: number;
  total_reviews?: number;
  total_versions?: number;
  total_changes?: number;
  recent_reviews?: DashboardResourceRecentReviewsItem[];
  recent_changes?: DashboardResourceRecentChangesItem[];
}
