/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { GetChartsCollection } from './getChartsCollection';
import type { GetChartsPlatform } from './getChartsPlatform';

export type GetChartsParams = {
platform: GetChartsPlatform;
collection: GetChartsCollection;
country?: string;
category_id?: number;
};
