/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { ReviewSummaryResourceDistribution } from './reviewSummaryResourceDistribution';

export interface ReviewSummaryResource {
  total_reviews?: number;
  average_rating?: number;
  distribution?: ReviewSummaryResourceDistribution;
  countries?: string[];
}
