/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * AppStoreCat API
 * Open source app intelligence toolkit API. Provides endpoints for app registration, DNA building, store listing tracking, and analytics.
 * OpenAPI spec version: 1.0.0
 */

export interface Review {
  id?: number;
  country_code?: string;
  /** @nullable */
  external_id?: string | null;
  /** @nullable */
  author?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  body?: string | null;
  rating?: number;
  /** @nullable */
  review_date?: string | null;
  /** @nullable */
  app_version?: string | null;
}
