[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:sync-tracked-ios]
command=/usr/local/bin/php /var/www/html/artisan queue:work --queue=sync-tracked-ios --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopwaitsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:sync-tracked-android]
command=/usr/local/bin/php /var/www/html/artisan queue:work --queue=sync-tracked-android --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopwaitsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:sync-on-demand-ios]
command=/usr/local/bin/php /var/www/html/artisan queue:work --queue=sync-on-demand-ios --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopwaitsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:sync-on-demand-android]
command=/usr/local/bin/php /var/www/html/artisan queue:work --queue=sync-on-demand-android --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopwaitsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:charts-ios]
command=/usr/local/bin/php /var/www/html/artisan queue:work --queue=charts-ios --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopwaitsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:charts-android]
command=/usr/local/bin/php /var/www/html/artisan queue:work --queue=charts-android --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopwaitsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scheduler]
command=/usr/local/bin/php /var/www/html/artisan schedule:work
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
